In [18]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import seaborn as sns

rng = np.random.default_rng(1) # set random seed for reproducibility
penguins = sns.load_dataset("penguins").dropna(subset=['body_mass_g'])

In [19]:
# Challenge 01
# 1.1 Isolate Adelie penguins for analysis [1 pt]

# If you haven't already, familiarize yourself with the penguins DataFrame (you can read more in the official docs). 
# Then make a new DataFrame, adelie, which contains only penguins whose species is Adelie. 

adelie = penguins[penguins['species'] == 'Adelie']
adelie

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,Female
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female
149,Adelie,Dream,37.8,18.1,193.0,3750.0,Male
150,Adelie,Dream,36.0,17.1,187.0,3700.0,Female
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male

In [20]:
# 1.2 Calculate summary statistics about penguin body mass [2 pts]

# Then, calculate the following summary statistics about Adelie penguin's body mass in grams (the feature body_mass_g):

#     The median value, and save as median_mass
#     The mean value, and save as mean_mass
#     The 5th percentile, and save as pctile_5_mass
#     The 95th percentile, and save as pctile_95_mass
#     The standard deviation, and save as std_mass
#     The interquartile range, and save as iqr_mass

# Hint: Be mindful of missing values in this problem.

median_mass    = adelie.body_mass_g.median(skipna=True)
mean_mass      = adelie.body_mass_g.mean(skipna=True)
pctile_5_mass  = adelie.body_mass_g.quantile(0.05)
pctile_95_mass = adelie.body_mass_g.quantile(0.95)
std_mass       = adelie.body_mass_g.std(skipna=True)
iqr_mass       = adelie.body_mass_g.quantile(0.75) - adelie.body_mass_g.quantile(0.25)

In [21]:
# 1.3 Calculate the percentile of observations [2 pts]

# Using the distribution of body mass in adelie, what would be the corresponding percentile of the following observations? 
# Your answer should be correct within 1 percentage point. You should omit any nan values in these calculations.
    # Penguin A weighs 4000 g; save the percentile as penguin_a_pctile
    # Penguin B weighs 3300 g; save the percentile as penguin_b_pctile
    # Penguin C weighs 4500 g; save the percentile as penguin_c_pctile


penguin_a_pctile = stats.percentileofscore(adelie['body_mass_g'], 4000)
penguin_b_pctile = stats.percentileofscore(adelie['body_mass_g'], 3300)
penguin_c_pctile = stats.percentileofscore(adelie['body_mass_g'], 4500)

In [39]:
# 1.4 Calculate z-scores [1 pts]¶
# Create a new column in adelie called body_mass_z, which is the z-score of body mass in grams for Adelie penguins.

adelie['body_mass_z'] = stats.zscore(adelie.body_mass_g, nan_policy='omit')

In [41]:
adelie

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_z
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0.107949
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0.217348
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.986034
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-0.548441
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.110847
...,...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,Female,-0.493742
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female,-0.548441
149,Adelie,Dream,37.8,18.1,193.0,3750.0,Male,0.107949
150,Adelie,Dream,36.0,17.1,187.0,3700.0,Female,-0.001449
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male,0.654941

In [24]:
# Using the new z-score feature, segment the data into the following new DataFrames:
    # middle_68, the middle 68% of the body mass distribution
    # middle_95, the middle 95% of the body mass distribution
    # top_16, the top 16% of the body mass distribution
    # bottom_50, the bottom 50% of the body mass distribution

middle_68 = adelie[adelie['body_mass_z'].between(-1, 1)]
middle_95 = adelie[adelie['body_mass_z'].between(-2, 2)]
top_16    = adelie[adelie['body_mass_z'] > 1]
bottom_50 = adelie[adelie['body_mass_z'] < 0]

In [ ]:
# 2.1 Investigating relationships in penguin body measurements [2 pts]

# Using the adelie DataFrame, fit a linear model of how body mass (body_mass_g) relates to flipper length (flipper_length_mm). 
# The dependent variable should be body_mass_g. Save the linear model as adelie_mass_lm.

# Note: you will not be able to fit a linear model if any NaN values are present in the variables to be modeled. 
# Therefore, you must first remove any rows from adelie where a NaN is present in either flipper_length or body_mass_g. 
# Do not use NaN values in other columns as an exclusion criteria.

# adelie_mass_lm = pd.DataFrame({'body mass': adelie.body_mass_g, 'flipper length': adelie.flipper_length_mm})

adelie_mass_lm = stats.linregress( x=adelie['flipper_length_mm'], y=adelie['body_mass_g'] )
adelie_mass_lm

LinregressResult(slope=np.float64(32.83168975115009), intercept=np.float64(-2535.8368022002514), rvalue=np.float64(0.46820169421793933), pvalue=np.float64(1.3432645947790076e-09), stderr=np.float64(5.076138407990821), intercept_stderr=np.float64(964.7984274994059))

In [42]:
# Using the model estimated above, make the following calculations:
    # What would be the predicted body mass in grams of an Adelie penguin with 200 mm long flippers? Save this calculation as prediction_200mm.
    # What would be the predicted body mass in grams of an Adelie penguin with 180 mm long flippers? Save this calculation as prediction_180mm.
    # What percent of variance in body mass in grams is explained by flipper length? Save this calculation as variance_explained_by_flipper_length.

# Answers should be correct within 1 decimal place.

def predict_adelie_weight(flipper_length):
    weight = (adelie_mass_lm.slope * flipper_length) + adelie_mass_lm.intercept
    return weight

prediction_200mm = predict_adelie_weight(200)
prediction_180mm = predict_adelie_weight(180)
variance_explained_by_flipper_length = (adelie_mass_lm.rvalue ** 2)

print(f"Predicted body mass of an Adelie penguin with 200 mm long flippers is {prediction_200mm:.1f} grams.")
print(f"Predicted body mass of an Adelie penguin with 180 mm long flippers is {prediction_180mm:.1f} grams.")
print(f"Variance in body mass as explained by flipper length is {variance_explained_by_flipper_length * 100:.1f} %")

Predicted body mass of an Adelie penguin with 200 mm long flippers is 4030.5 grams.
Predicted body mass of an Adelie penguin with 180 mm long flippers is 3373.9 grams.
Variance in body mass as explained by flipper length is 21.9 %