## Machine Learning Foundation

### Section 1, Part A: Reading Data

In [1]:
import sqlite3 as sq3
import pandas.io.sql as pds
import pandas as pd

In [2]:
path = "data/classic_rock.db"
con = sq3.Connection(path)

#### Reading data
Now that we've got a connection to our database, we can perform queries, and load their results in as Pandas DataFrames.

In [3]:
query = '''SELECT * FROM rock_songs;'''
observations = pds.read_sql(query, con)

observations.head()

                     Song        Artist  Release_Year  PlayCount
0        Caught Up in You   .38 Special        1982.0         82
1         Hold On Loosely   .38 Special        1981.0         85
2  Rockin' Into the Night   .38 Special        1980.0         18
3       Art For Arts Sake          10cc        1975.0          1
4              Kryptonite  3 Doors Down        2000.0         13

In [4]:
query = '''
SELECT Artist, Release_year, COUNT(*) AS num_songs, AVG(PlayCount) AS avg_plays
FROM rock_songs
GROUP BY Artist, Release_Year
ORDER BY num_songs DESC;
'''

observations_generator = pds.read_sql(query,
                                      con,
                                      coerce_float=True, # attempt to force number into floats (does not effect this dataset because floats were correctly parsed).
                                      parse_dates=['Release_Year'], # parse 'Release_Year' as a date
                                      chunksize=5 # Allows for streaming results as a series of shorter tables in chunk of 5 rows; this which gives us observations_generator
                            )

for index, observations in enumerate(observations_generator):
    if index < 5:
        print(f"Observations index: {index}".format(index))
        display(observations)

Observations index: 0

         Artist        Release_Year  num_songs  avg_plays
0   The Beatles 1970-01-01 00:32:47         23   6.565217
1  Led Zeppelin 1970-01-01 00:32:49         18  21.000000
2   The Beatles 1970-01-01 00:32:45         15   3.800000
3   The Beatles 1970-01-01 00:32:48         13  13.000000
4   The Beatles 1970-01-01 00:32:49         13  15.000000

Observations index: 1

         Artist        Release_Year  num_songs  avg_plays
0  Led Zeppelin 1970-01-01 00:32:50         12  13.166667
1  Led Zeppelin 1970-01-01 00:32:55         12  14.166667
2    Pink Floyd 1970-01-01 00:32:59         11  41.454545
3    Pink Floyd 1970-01-01 00:32:53         10  29.100000
4     The Doors 1970-01-01 00:32:47         10  28.900000

Observations index: 2

          Artist        Release_Year  num_songs  avg_plays
0  Fleetwood Mac 1970-01-01 00:32:57          9  35.666667
1   Jimi Hendrix 1970-01-01 00:32:47          9  24.888889
2    The Beatles 1970-01-01 00:32:43          9   2.444444
3    The Beatles 1970-01-01 00:32:44          9   3.111111
4     Elton John 1970-01-01 00:32:53          8  18.500000

Observations index: 3

           Artist        Release_Year  num_songs  avg_plays
0    Led Zeppelin 1970-01-01 00:32:51          8  47.750000
1    Led Zeppelin 1970-01-01 00:32:53          8  34.125000
2          Boston 1970-01-01 00:32:56          7  69.285714
3  Rolling Stones 1970-01-01 00:32:49          7  36.142857
4       Van Halen 1970-01-01 00:32:58          7  51.142857

Observations index: 4

                         Artist        Release_Year  num_songs  avg_plays
0             Bruce Springsteen 1970-01-01 00:32:55          6   7.666667
1             Bruce Springsteen 1970-01-01 00:33:04          6  11.500000
2  Creedence Clearwater Revival 1970-01-01 00:32:49          6  23.833333
3  Creedence Clearwater Revival 1970-01-01 00:32:50          6  18.833333
4                   Def Leppard 1970-01-01 00:33:07          6  32.000000

### Section 1, Part b: Reading Data Lab


#### Lab Exercise: Reading in database files
 - Create a variable, `path`, containing the path to the `baseball.db` contained in `resources/`
 - Create a connection, `con`, that is connected to database at `path`
 - Create a variable, `query`, containing a SQL query which reads in all data from the `allstarfull` table
 - Create a variable, `observations`, by using pandas' [read_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)

#### Optional
 - Create a variable, `tables`, which reads in all data from the table `sqlite_master`
 - Pretend that you were interesting in creating a new baseball hall of fame. Join and analyze the tables to evaluate the top 3 all time best baseball players.

In [5]:
path = "data/baseball.db"
con = sq3.Connection(path)

query = '''SELECT * FROM allstarfull;'''
observations = pds.read_sql(query, con, index_col='index')

observations.head()

        playerID  yearID  gameNum        gameID teamID lgID   GP  startingPos
index
0      gomezle01    1933        0  ALS193307060    NYA   AL  1.0          1.0
1      ferreri01    1933        0  ALS193307060    BOS   AL  1.0          2.0
2      gehrilo01    1933        0  ALS193307060    NYA   AL  1.0          3.0
3      gehrich01    1933        0  ALS193307060    DET   AL  1.0          4.0
4      dykesji01    1933        0  ALS193307060    CHA   AL  1.0          5.0

In [6]:
query = '''SELECT * FROM sqlite_master;'''
tables = pds.read_sql(query, con)

tables

,type,name,tbl_name,rootpage,sql
0,table,allstarfull,allstarfull,2,"CREATE TABLE ""allstarfull"" (\n""index"" INTEGER,..."
1,index,ix_allstarfull_index,allstarfull,3,"CREATE INDEX ""ix_allstarfull_index""ON ""allstar..."
2,table,schools,schools,26,"CREATE TABLE ""schools"" (\n""index"" INTEGER,\n ..."
3,index,ix_schools_index,schools,31,"CREATE INDEX ""ix_schools_index""ON ""schools"" (""..."
4,table,batting,batting,99,"CREATE TABLE ""batting"" (\n""index"" INTEGER,\n ..."
5,index,ix_batting_index,batting,100,"CREATE INDEX ""ix_batting_index""ON ""batting"" (""..."

In [7]:
best_query = """
SELECT playerID, sum(GP) AS num_games_played, AVG(startingPos) AS avg_starting_position
    FROM allstarfull
    GROUP BY playerID
    ORDER BY num_games_played DESC, avg_starting_position ASC
    LIMIT 3
"""
best = pd.read_sql(best_query, con)
print(best.head())

    playerID  num_games_played  avg_starting_position
0  musiast01              24.0               6.357143
1   mayswi01              24.0               8.000000
2  aaronha01              24.0               8.470588