# Ensemble Classifiers

Think of all the previous models (Logistic Regression, KNN, SVM, Decision Tree) as individual experts. Sometimes an expert has a blind spot. An Ensemble Classifier is like putting a panel of these experts in a room, letting them all vote, and taking the majority decision. Because it aggregates multiple perspectives, the panel is almost always more accurate and robust than any single expert alone.

Here is a breakdown of how ensemble learning works, focusing on Bagging, Random Forest, and Extra Trees, and how they contrast with what we've learned so far.

### 1. The Core Concepts

**Ensemble Classifier**

An ensemble method combines the predictions of multiple base estimators (usually weak or diverse models) to create a single, stronger predictive model. The goal is to reduce variance (overfitting) or bias (underfitting).

**Bagging (Bootstrap Aggregating)**

Bagging is the foundational technique for the models we are discussing. It works on a simple principle: **Parallel Democracy**. Bagging is a general methodology. It says: "Let's take any base model, create random subsets of the data with replacement, train a model on each, and vote." You could technically use Bagging with Logistic Regression or Support Vector Machines as the base models.

* **Bootstrap**: The algorithm creates multiple subsets of your original dataset by sampling the data randomly with replacement. This means some rows will be repeated in a subset, and others will be left out.

* **Aggregating**: A separate base model (usually a Decision Tree) is trained independently on each subset. For a classification task, when a new data point arrives, every tree casts a vote, and the majority vote wins.

<BR>

**Random Forest**

Random Forest takes Bagging a step further by introducing feature randomness. In short, it is a specific type of Bagging Implementation. It dictates that the base models must be Decision Trees, and it adds that extra rule as discussed: forcing the trees to only look at a random subset of features at each split to ensure they don't all look identical.

* In standard Bagging with Decision Trees, if one or two features are incredibly dominant predictors, almost all the trees will choose to split on those same features first. This makes the trees highly correlated.

* Random Forest forces diversity: when splitting a node, it only considers a random subset of features rather than all available features. This decorrelates the trees, ensuring they look at the data from wildly different angles.

<BR>

**Extra Trees (Extremely Randomized Trees)**

Extra Trees takes the randomness of a Random Forest and turns it up to eleven.

* Like Random Forest, it selects a random subset of features at each node.

* However, instead of looking for the most optimal split point (threshold) among those features using mathematical metrics like Gini impurity or Entropy, Extra Trees chooses a split point entirely at random for each feature and picks the best of those random options.

* Why do this? It makes training incredibly fast computationally, and the extreme randomness reduces variance even further (though it might slightly increase bias).

<BR>

### 2. How They Contrast with Previous Classifiers

To see why ensembles are so powerful, let's contrast them with the individual models:

|Classifier|How it Learns|The Vulnerability|The Ensemble Fix|
|---|---|---|---|
|Decision Tree|Splits data sequentially based on feature thresholds.|Highly prone to overfitting (high variance). A small change in data changes the whole tree.|"Random Forest / Extra Trees average out dozens or hundreds of trees, canceling out individual overfitting."|
|KNN|Looks at the geometric proximity of the nearest k neighbors.|Strugglers with high-dimensional data (curse of dimensionality) and is computationally slow at scale.|Ensembles handle high-dimensional feature spaces much better due to feature subsetting.|
|SVM|Finds the optimal hyperplane that maximizes the margin between classes.|Highly sensitive to noise/outliers near the decision boundary.|Bagging reduces sensitivity to outliers because no single tree sees the entire dataset.|
|Logistic Regression|Finds a linear boundary using a sigmoidal probability curve.|"High bias; cannot naturally capture complex, non-linear relationships without manual feature engineering."|"Ensembles natively capture intricate, non-linear patterns without extra feature engineering."|

<BR>

### Summary of the Shift in Philosophy

When we move into ensembles, we stop trying to build the "perfect" flawless model. Instead, we accept that individual trees will make mistakes, but we rely on the mathematical truth that independent errors cancel out in a crowd.

* Bagging gives you a crowd of trees.

* Random Forest ensures the crowd is diverse by limiting what they can see.

* Extra Trees makes the crowd make decisions faster by introducing random choices.

##

___

# Random Forests (RF) for classification - Practice Lab

Estimated time needed: **45** minutes

## Objectives

After completing this lab you will be able to:

*   Understand the difference between Bagging and Random Forest
*   Understand  that Random Forests have less Correlation between predictors in their ensemble, improving accuracy
*   Apply Random Forest
*   Understand Hyperparameters selection in  Random Forest

In this notebook, you will learn Random Forests (RF) for classification and Regression. Random Forest is similar to Bagging using multiple model versions and aggregating the ensemble of models to make a single prediction. RF uses an ensemble of tree’s and introduces randomness into each tree by randomly selecting a subset of the features for each node to split on. This makes the predictions of each tree uncorrelated, improving results when the models are aggregated. In this lab, we will illustrate the sampling process of RF to Bagging, then demonstrate how each predictor for random forest are not correlated. Finally, we will apply Random Forests to several datasets using Grid-Search to find the optimum  Hyperparameters.

<h1>Table of contents</h1>

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ol>
        <li><a href="https://#RFvsBag">What's the difference between RF and Bagging </a></li>
        <li><a href="https://#Example">Cancer Data Example</li>
        <li><a href="https://practice/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML241ENSkillsNetwork31576874-2022-01-01">Practice</a></li>

</div>
<br>
<hr>

Let's first import the required libraries:

In [1]:
import pandas as pd
import pylab as plt
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing

import matplotlib.pyplot as plt
from sklearn import metrics
from tqdm import tqdm

This function will calculate the accuracy of the training and testing data given a model.

In [2]:
def get_accuracy(X_train, X_test, y_train, y_test, model):
    return  {"Testing Accuracy":metrics.accuracy_score(y_test, model.predict(X_test)),"Training Accuracy": metrics.accuracy_score(y_train, model.predict(X_train))}

This function calculates the average correlation between predictors and displays the pairwise correlation between  predictors.

In [3]:
#This function calculates the average correlation between predictors  

def get_correlation(X_test, y_test, models):
    n_estimators = len(models.estimators_)
    prediction = np.zeros((y_test.shape[0], n_estimators))
    predictions = pd.DataFrame({'estimator '+str(n+1):[] for n in range(n_estimators)})
    
    for key,model in zip(predictions.keys(),models.estimators_):
        predictions[key] = model.predict(X_test.to_numpy())
    
    corr = predictions.corr()
    print("Average correlation between predictors: ", corr.mean().mean() - 1/n_estimators)
    return corr

<h2 id="RFvsBag">  What's the difference between RF and Bagging </h2>

RF is a specific implementation of Bagging in that it uses model ensembles to make predictions. Unlike Bagging, when you add more models, RF does not suffer from Overfitting. In this section, we go over some of the differences between RF and Bagging, using the dataset:

### About the dataset

We will use a telecommunications dataset for predicting customer churn. This is a historical customer dataset where each row represents one customer. The data is relatively easy to understand, and you may uncover insights you can use immediately. Typically, it is less expensive to keep customers than acquire new ones, so the focus of this analysis is to predict the customers who will stay with the company.

This data set provides information to help you predict what behavior will help you to retain customers. You can analyze all relevant customer data and develop focused customer retention programs.

The dataset includes information about:

*   Customers who left within the last month – the column is called Churn
*   Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
*   Customer account information – how long they had been a customer, contract, payment method, paperless billing, monthly charges, and total charges
*   Demographic info about customers – gender, age range, and if they have partners and dependents

Load Data From CSV File

In [4]:
# data_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv"

churn_df = pd.read_csv("data/ChurnData.csv")

churn_df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0

### Data pre-processing and feature selection

Let's select some features for the modeling. Also, we change the target data type to be an integer, as it is a requirement by the skitlearn algorithm:

In [5]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip', 'callcard', 'wireless','churn']]
churn_df['churn'] = churn_df['churn'].astype('int')
churn_df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0

### Bootstrap Sampling

Bootstrap Sampling is a method that involves drawing sample data repeatedly with replacement from a data source to estimate a model parameter. Scikit-learn has methods for Bagging, but it is helpful to understand Bootstrap Sampling. We will import "resample".

In [6]:
from sklearn.utils import resample

Consider the first five rows of data:

In [7]:
churn_df[0:5]

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0

We can perform a bootstrap sample using the function "resample"; we see the dataset is of the same size(5), but some rows are repeated:

In [8]:
for n in range(5):
    display(resample(churn_df[0:5]))

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1

### Select Variables at Random

Like Bagging, RF uses an independent bootstrap sample from the training data. In addition, we select $m$ variables at random out of all $M$ possible
variables. Let's do an example.

In [9]:
X = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']]

there are 7 features

In [10]:
M = X.shape[1]
M

7

Let us select $𝑚=3$, and randomly sample features from the 5 Bootstrap Samples from above.

In [11]:
m = 3

We list out the index of the features

In [12]:
feature_index = range(M)
feature_index

range(0, 7)

We can use the function to sample to  randomly select indexes

In [13]:
import random
random.sample(feature_index, m)

[1, 5, 2]

We now randomly select features from the bootstrap samples to randomly select a subset of features for each node to split on.

In [14]:
for n in range(5):
    print("sample {}".format(n))
    print(resample(X[0:5]).iloc[:,random.sample(feature_index,m)])
    print()

sample 0
   income  address   ed
2    30.0      9.0  1.0
0   136.0      7.0  5.0
4    80.0     14.0  2.0
3    76.0      5.0  2.0
3    76.0      5.0  2.0

sample 1
   income  tenure  equip
1    33.0    33.0    0.0
3    76.0    38.0    1.0
4    80.0     7.0    0.0
4    80.0     7.0    0.0
2    30.0    23.0    0.0

sample 2
   employ  equip   ed
4    15.0    0.0  2.0
3    10.0    1.0  2.0
3    10.0    1.0  2.0
3    10.0    1.0  2.0
2     2.0    0.0  1.0

sample 3
   employ  address  tenure
2     2.0      9.0    23.0
3    10.0      5.0    38.0
2     2.0      9.0    23.0
4    15.0     14.0     7.0
1     0.0     12.0    33.0

sample 4
   address   age   ed
0      7.0  33.0  5.0
0      7.0  33.0  5.0
1     12.0  33.0  2.0
0      7.0  33.0  5.0
4     14.0  35.0  2.0

In Random Forest, we would use these data subsets to train each node of a tree.

## Train/Test dataset

Let's define X, and y for our dataset:

In [15]:
y = churn_df['churn']
y.head()

0    1
1    1
2    0
3    0
4    0
Name: churn, dtype: int64

## Train/Test dataset

We split our dataset into train and test set:

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=1)
print ('Train set', X_train.shape,  y_train.shape)
print ('Test set', X_test.shape,  y_test.shape)

Train set (140, 7) (140,)
Test set (60, 7) (60,)

### Bagging  Review

In [17]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

Bagging improves models that suffer from overfitting; they do well on the training data, but they do not generalize well to unseen data. Decision Trees are a prime candidate for this reason. In addition, they are fast to train; We create a <code>BaggingClassifier</code> object,  with a Decision Tree as the <code>estimator</code>.

In [18]:
n_estimators=20
Bag = BaggingClassifier(estimator = DecisionTreeClassifier(criterion="entropy", max_depth=4, random_state=2), n_estimators=n_estimators, random_state=0, bootstrap=True)

We fit the model:

In [19]:
Bag.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(criterion='entropy',
                                                   max_depth=4,
                                                   random_state=2),
                  n_estimators=20, random_state=0)

The method <code>predict</code> aggregates the predictions by voting:

In [20]:
Bag.predict(X_test).shape

(60,)

We see the training accuracy is slightly better but the test accuracy improves dramatically:

In [21]:
print(get_accuracy(X_train, X_test, y_train, y_test,  Bag))

{'Testing Accuracy': 0.7333333333333333, 'Training Accuracy': 0.9071428571428571}

Each tree is similar; we can see this by plotting the correlation between each tree and the average correlation.

In [22]:
get_correlation(X_test, y_test,Bag).style.background_gradient(cmap='coolwarm')

Average correlation between predictors:  0.25400671537472364

It can be shown that this correlation reduces performance. Random forest minimizes the correlation between trees, improving results.

## Random  Forest

Random forests are a combination of trees such that each tree depends on a random subset of the features and data. As a result, each tree in the forest is different and usually performs better than Bagging. The most important parameters are the number of trees and the number of features to sample. First, we import <code>RandomForestClassifier</code>.

In [23]:
from sklearn.ensemble import RandomForestClassifier

Like Bagging, increasing the number of trees improves results and does not lead to overfitting in most cases; but the improvements plateau as you add more trees. For this exxample, the number of trees in the forest (default=100):

In [24]:
n_estimators = 20

<code>max_features </code>   $m$ the number of features to consider when looking for the best split. If we have M features denoted by:

In [25]:
M_features = X.shape[1]

If we have M features, a popular method to determine m is to use the square root of M

$m= floor(\sqrt{M}) $

We use floor to make sure $m$ is an integer:

In [26]:
max_features = round(np.sqrt(M_features)) - 1
max_features

2

In [27]:
y_test

58     1
40     0
34     0
102    0
184    0
198    1
95     1
4      0
29     0
168    0
171    1
18     0
11     0
89     0
110    0
118    0
159    1
35     0
136    1
59     0
51     0
16     0
44     0
94     0
31     0
162    0
38     0
28     0
193    0
27     0
47     0
165    0
194    0
177    0
176    0
97     1
174    1
73     0
69     0
172    1
108    0
107    1
189    0
14     0
56     0
19     1
114    0
39     0
185    0
124    0
98     0
123    1
119    0
53     0
33     1
179    0
181    0
106    0
199    0
138    1
Name: churn, dtype: int64

We create the RF object :

In [28]:
model = RandomForestClassifier( max_features=max_features, n_estimators=n_estimators, random_state=0)

We train the model

In [29]:
model.fit(X_train,y_train)

RandomForestClassifier(max_features=2, n_estimators=20, random_state=0)

We obtain the training and testing accuracy; we see that RF does better than Bagging:

In [30]:
print(get_accuracy(X_train, X_test, y_train, y_test, model))

{'Testing Accuracy': 0.8, 'Training Accuracy': 0.9857142857142858}

We see that each tree in RF is less correlated with the other trees than Bagging:

In [31]:
get_correlation(X_test, y_test,model).style.background_gradient(cmap='coolwarm')

Average correlation between predictors:  0.21335179318993674

<h2 id="Example">Cancer Data Example</h2>

The example is based on a dataset that is publicly available from the UCI Machine Learning Repository (Asuncion and Newman, 2007)[[http://mlearn.ics.uci.edu/MLRepository.html](http://mlearn.ics.uci.edu/MLRepository.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML241ENSkillsNetwork31576874-2022-01-01)]. The dataset consists of several hundred human cell sample records, each of which contains the values of a set of cell characteristics. The fields in each record are:

| Field name  | Description                 |
| ----------- | --------------------------- |
| ID          | Clump thickness             |
| Clump       | Clump thickness             |
| UnifSize    | Uniformity of cell size     |
| UnifShape   | Uniformity of cell shape    |
| MargAdh     | Marginal adhesion           |
| SingEpiSize | Single epithelial cell size |
| BareNuc     | Bare nuclei                 |
| BlandChrom  | Bland chromatin             |
| NormNucl    | Normal nucleoli             |
| Mit         | Mitoses                     |
| Class       | Benign or malignant         |

<br>
<br>

Let's load the dataset:

In [32]:
# data_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/cell_samples.csv"

df = pd.read_csv("data/cell_samples.csv")

df.head()

,ID,Clump,UnifSize,UnifShape,MargAdh,SingEpiSize,BareNuc,BlandChrom,NormNucl,Mit,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

Now lets remove rows that have a ? in the <code>BareNuc</code> column:

In [33]:
df = df[pd.to_numeric(df['BareNuc'], errors='coerce').notnull()]

We obtain the features:

In [34]:
X = df[['Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize', 'BareNuc', 'BlandChrom', 'NormNucl', 'Mit']]

X.head()

,Clump,UnifSize,UnifShape,MargAdh,SingEpiSize,BareNuc,BlandChrom,NormNucl,Mit
0,5,1,1,1,2,1,3,1,1
1,5,4,4,5,7,10,3,2,1
2,3,1,1,1,2,2,3,1,1
3,6,8,8,1,3,4,3,7,1
4,4,1,1,3,2,1,3,1,1

We obtain the class labels:

In [35]:
y = df['Class']
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

We split the data into training and testing sets.

In [36]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4 )

print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (546, 9) (546,)
Test set: (137, 9) (137,)

We use <code>GridSearchCV</code> to search over specified parameter values  of the model.

In [37]:
from sklearn.model_selection import GridSearchCV

We create a <code>RandomForestClassifier</code> object and list the parameters using the method <code>get_params()</code>:

In [38]:
model = RandomForestClassifier()
model.get_params().keys()

dict_keys(['bootstrap', 'ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'max_samples', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'monotonic_cst', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'])

We can use GridSearch for Exhaustive search over specified parameter values. We see many of the parameters are similar to Classification trees; let's try a different parameter for <code>max_depth</code>, <code>max_features</code> and <code>n_estimators</code>.

In [42]:
param_grid = {
                'n_estimators': [2*n+1 for n in range(20)],
                'max_depth'   : [2*n+1 for n in range(10)],
                'max_features': ["sqrt", "log2"]
            }

We create the Grid Search object and fit it:

In [43]:
search = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', error_score='raise')
search.fit(X_train, y_train)

GridSearchCV(error_score='raise', estimator=RandomForestClassifier(),
             param_grid={'max_depth': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                          23, 25, 27, 29, 31, 33, 35, 37, 39]},
             scoring='accuracy')

We can see the best accuracy score of the searched parameters was \~98%.

In [44]:
search.best_score_

np.float64(0.9780817347789826)

The best parameter values are:

In [45]:
search.best_params_

{'max_depth': 15, 'max_features': 'log2', 'n_estimators': 37}

We can calculate accuracy on the test data using the test data:

In [46]:

print(get_accuracy(X_train, X_test, y_train, y_test, search.best_estimator_))

{'Testing Accuracy': 0.9708029197080292, 'Training Accuracy': 1.0}

<h2 id="practice">Practice</h2>

Imagine that you are a medical researcher compiling data for a study. You have collected data about a set of patients, all of whom suffered from the same illness. During their course of treatment, each patient responded to one of 5 medications, Drug A, Drug B, Drug C, Drug X and Y.

Part of your job is to build a model to find out which drug might be appropriate for a future patient with the same illness. The features of this dataset are Age, Sex, Blood Pressure, and the Cholesterol of the patients, and the target is the drug that each patient responded to.

It is a sample of multiclass classifier, and you can use the training part of the dataset to build a decision tree, and then use it to predict the class of a unknown patient, or to prescribe a drug to a new patient.

In [47]:
# data_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv"

df = pd.read_csv("data/drug200.csv", delimiter=",")
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Let's create the X and y for our dataset:

In [48]:
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [49]:
y = df["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: str

Now lets use a <code>LabelEncoder</code> to turn categorical features into numerical:

In [ ]:
from sklearn import preprocessing

le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1]) 


le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])


le_Chol = preprocessing.LabelEncoder()
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3]) 

X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

Split the data into training and testing data with a 80/20 split

In [51]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 5) (160,)
Test set: (40, 5) (40,)

We can use GridSearch for Exhaustive search over specified parameter values.

In [52]:
param_grid = {'n_estimators': [2*n+1 for n in range(20)],
             'max_depth'    : [2*n+1 for n in range(10)],
             'max_features' : ["sqrt", "log2"]}

Create a <code>RandomForestClassifier </code>object called <cood>model</code> :

In [53]:
model = RandomForestClassifier()

Create <code>GridSearchCV</code> object called `search` with the `estimator` set to <code>model</code>, <code>param_grid</code> set to <code>param_grid</code>, <code>scoring</code> set to <code>accuracy</code>, and  <code>cv</code> set to 3 and Fit the <code>GridSearchCV</code> object to our <code>X_train</code> and <code>y_train</code> data

In [54]:
search = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=3, error_score='raise')
search.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise', estimator=RandomForestClassifier(),
             param_grid={'max_depth': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,
                                          23, 25, 27, 29, 31, 33, 35, 37, 39]},
             scoring='accuracy')

We can find the accuracy of the best model.

In [55]:
search.best_score_

np.float64(1.0)

We can find the best parameter values:

In [56]:
search.best_params_

{'max_depth': 5, 'max_features': 'log2', 'n_estimators': 23}

We can find the accuracy test data:

In [57]:
print(get_accuracy(X_train, X_test, y_train, y_test, search.best_estimator_))

{'Testing Accuracy': 0.925, 'Training Accuracy': 1.0}

### **Key Takeaway**

 **Bagging (with Decision Tree)** samples the rows randomly (with replacement) but gives every single tree the full set of features to choose from at every split.

 **Random Forest** samples the rows randomly (with replacement) AND samples a random subset of features at every single split point.

 Because standard Bagging looks at every feature, if there is one incredibly strong predictor in the dataset (for example, BareNuc in our cell samples dataset), almost every single tree in a standard Bagging ensemble will choose to split on BareNuc right at the very top. This results in a crowd of trees that all look remarkably similar.
 
 By forcing the trees to choose from a random subset of features, Random Forest ensures that some trees are forced to build logic without that dominant feature. This creates a much more diverse "council of experts."

It’s helpful to know when the feature randomness happens in a Random Forest, it doesn't just pick a random set of features for the entire tree at the beginning. Instead, it picks a new random subset of features at every single node split within every tree. So at Node 1, it might randomly choose to only look at Clump and Mit. Then, at the next branch down, it resets and randomly chooses to only look at UnifSize and BlandChrom.

When choosing features for a split, it is done without replacement. When a single node in a Random Forest tree goes to make a split, it looks at a completely unique bucket of candidate features. For example, if your max_features is set to 3, the algorithm will randomly grab 3 distinct features from the data (e.g., ['Clump', 'Mit', 'UnifSize']). It won't pick ['Clump', 'Clump', 'UnifSize'].

To keep the concepts clear, here is how the two types of randomness in Random Forest handle replacement:

|Component|Random Selection Method|With or Without Replacement?|Why?|
|---|---|---|---|
|Data Rows (Bootstrapping)|Randomly selects rows for the tree's dataset.|With Replacement|"This ensures each tree gets a slightly different variation of the data, leaving about 36.8% of the rows out as ""validation"" data (called Out-Of-Bag data)."|
|Features (At each split)|Randomly selects a subset of columns to evaluate.|Without Replacement|Selecting the same feature multiple times in a single subset would defeat the purpose of giving the node a diverse selection of attributes to choose from.|

<BR>

#### How it looks step-by-step at a node split:

1. The Reset: The algorithm looks at all available features in your dataset.

2. The Draw: It randomly pulls out m features without replacement (where m is your max_features setting, like sqrt).

3. The Winner: It evaluates only those m features, finds the absolute best split point among them, splits the node, and then throws all the features back into the main pool.

4. The Next Node: For the very next split down the branch, it repeats the process, drawing a brand-new, distinct random batch.

This is why Random Forests are so remarkably robust—the features have to fight a brand new, randomized lottery at every single intersection of the tree!

<BR>

___