## Methods and Attributes between Series and DataFrames
#### Series and DataFrames have many methods and attributes in common, but they also have some that are unique to each type. Here are some of the key differences:
#### 1. Methods:
* Series:
    * `Series.mean()`: Calculates the mean of the values in the Series.
    * `Series.median()`: Calculates the median of the values in the Series.
    * `Series.mode()`: Calculates the mode of the values in the Series.
    * `Series.value_counts()`: Counts the unique values in the Series and returns a Series with the counts.
    * `Series.unique()`: Returns the unique values in the Series.
* DataFrame:
    * `DataFrame.mean()`: Calculates the mean of the values in each column of the DataFrame.
    * `DataFrame.median()`: Calculates the median of the values in each column of the DataFrame.
    * `DataFrame.mode()`: Calculates the mode of the values in each column of the DataFrame.
    * `DataFrame.value_counts()`: Counts the unique values in each column of the DataFrame and returns a DataFrame with the counts.
    * `DataFrame.unique()`: Returns the unique values in each column of the DataFrame.
#### 2. Attributes:
* Series:
    * `Series.name`: The name of the Series.
    * `Series.index`: The index of the Series.
    * `Series.dtype`: The data type of the values in the Series.
* DataFrame:
    * `DataFrame.columns`: The column names of the DataFrame.
    * `DataFrame.index`: The index of the DataFrame.
    * `DataFrame.dtypes`: The data types of the columns in the DataFrame.
    * `DataFrame.shape`: The shape of the DataFrame (number of rows and columns).
    * `DataFrame.info()`: Provides a summary of the DataFrame, including the number of non-null values, data types, and memory usage.
 
 These are just a few examples of the methods and attributes that are unique to Series and DataFrames. 
 Both Series and DataFrames have many other methods and attributes that can be used for data manipulation and analysis.

In [98]:
import pandas as pd

In [99]:
nba = pd.read_csv("data/nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
nba.values # Returns the underlying numpy array of the DataFrame.

array([['Saddiq Bey', 'Atlanta Hawks', 'F', ..., 215.0, 'Villanova',
        4556983.0],
       ['Bogdan Bogdanovic', 'Atlanta Hawks', 'G', ..., 225.0,
        'Fenerbahce', 18700000.0],
       ['Kobe Bufkin', 'Atlanta Hawks', 'G', ..., 195.0, 'Michigan',
        4094244.0],
       ...,
       ['Tristan Vukcevic', 'Washington Wizards', 'F', ..., 220.0,
        'Real Madrid', nan],
       ['Delon Wright', 'Washington Wizards', 'G', ..., 185.0, 'Utah',
        8195122.0],
       [nan, nan, nan, ..., nan, nan, nan]], shape=(592, 7), dtype=object)

In [101]:
nba.index # Returns the index of the DataFrame, which is a RangeIndex in this case.

RangeIndex(start=0, stop=592, step=1)

In [102]:
nba.shape # Returns the shape of the DataFrame as a tuple (number of rows, number of columns).

(592, 7)

In [103]:
nba.dtypes # Returns the data types of each column in the DataFrame.

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [104]:
nba.columns # Returns the column names of the DataFrame.

Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')

In [105]:
nba.axes # Returns the axes of the DataFrame, which is a list containing the index and columns.

[RangeIndex(start=0, stop=592, step=1),
 Index(['Name', 'Team', 'Position', 'Height', 'Weight', 'College', 'Salary'], dtype='str')]

In [106]:
nba.info() # Provides a summary of the DataFrame, including the number of non-null values, data types, and memory usage.

<class 'pandas.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    str
 1   Team      591 non-null    str
 2   Position  584 non-null    str
 3   Height    585 non-null    str
 4   Weight    584 non-null    float64
 5   College   578 non-null    str
 6   Salary    488 non-null    float64
dtypes: float64(2), str(5)
memory usage: 32.5 KB

## Differences between Shared Methods
    * The sum method adds a Series values
    * On a Dataframe, the sum method defaults to adding the values by traversing the index (row values)
    * The axis parameter customizes the direction that we add across. Pass "columns" or 1 to add "across" the columns

In [107]:
revenue = pd.read_csv("data/revenue.csv", index_col="Date") # Reads a CSV file and sets the "Date" column as the index of the resulting DataFrame.
revenue

         New York  Los Angeles  Miami
Date
1/1/26        985          122    499
1/2/26        738          788    534
1/3/26         14           20    933
1/4/26        730          904    885
1/5/26        114           71    253
1/6/26        936          502    497
1/7/26        123          996    115
1/8/26        935          492    886
1/9/26        846          954    823
1/10/26        54          285    216

In [108]:
s = pd.Series([1, 2, 3])
s.sum()

np.int64(6)

In [109]:
# A Series is 1D and a sum() method automatically sums up the values in one direction (rows), while a DataFrame is 2D and a sum() method 
# sums up the values in both directions (columns and rows) by default. Both Series and DataFrame will traverse the values on its index and 
# sum up the values in the column. Since a Series has only one column, it will just sum up that column. On the other hand, a DataFrame has 
# multiple columns, so it will sum up each column separately and return a Series with the sums of each column.
revenue.sum() # Sums up the values in each column of the DataFrame.

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [110]:
revenue.sum().sum() # sums up everything in the DataFrame, first summing each column and then summing those sums together.

np.int64(16250)

In [111]:
# Since DataFrame has multiple columns, the sum() method also provides an option to specify the axis along which to perform the summation. 
# By default, it sums along the columns (axis=0), but you can also sum along the rows (axis=1) by passing the appropriate argument to the sum() method.
revenue.sum(axis=1) # Sums up the values in each row of the DataFrame, i.e., it sums across the columns of New York, San Francisco, and Los Angeles for each row.

Date
1/1/26     1606
1/2/26     2060
1/3/26      967
1/4/26     2519
1/5/26      438
1/6/26     1935
1/7/26     1234
1/8/26     2313
1/9/26     2623
1/10/26     555
dtype: int64

In [112]:
revenue.sum(axis="columns").sum() # Sums up the values in each row of the DataFrame, using the string "columns" as an alternative to axis=1.

np.int64(16250)

## Select One Column from a Dataframe
    * use attribute syntax(df.column_name) to select a column from a Dataframe. Only works with column name without spaces.
    * use square bracket syntax (df["column_name"]) which works with spaces.
    * Pandas extracts a column from a Dataframe as a Series.
    * The Series is a view, however as of Pandas 3.0, modifying the Series will result in a copy and the changes will NOT affects the original Dataframe.

In [113]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
nba.Team # Accesses the "Team" column of the DataFrame, returning a Series containing the team names.

0           Atlanta Hawks
1           Atlanta Hawks
2           Atlanta Hawks
3           Atlanta Hawks
4           Atlanta Hawks
              ...
587    Washington Wizards
588    Washington Wizards
589    Washington Wizards
590    Washington Wizards
591                   NaN
Name: Team, Length: 592, dtype: str

In [115]:
nba["Team"] # Another way to access the "Team" column of the DataFrame, which also returns a Series containing the team names.

0           Atlanta Hawks
1           Atlanta Hawks
2           Atlanta Hawks
3           Atlanta Hawks
4           Atlanta Hawks
              ...
587    Washington Wizards
588    Washington Wizards
589    Washington Wizards
590    Washington Wizards
591                   NaN
Name: Team, Length: 592, dtype: str

In [116]:
# Note that as of Pandas 3.0, accessing a column of a DataFrame returns a view of the underlying data, not a copy. However, when we assign the view to a variable and attempt
# to modify it, it actually creates a copy of the data and the modification is not reflected in the original DataFrame. 
# To modify the original DataFrame, you should use .loc or .iloc to ensure that you are modifying the original DataFrame directly. For example, you can use nba.loc[0, "Salary"] = 0 instead.
s = nba["Salary"]
s.iloc[0] = 0 
s

0             0.0
1      18700000.0
2       4094244.0
3      20616000.0
4       2581522.0
          ...
587     1719864.0
588    10250000.0
589           NaN
590     8195122.0
591           NaN
Name: Salary, Length: 592, dtype: float64

In [117]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
nba["Salary"].iloc[0] = 0
nba

/tmp/ipykernel_6427/3420902171.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  nba["Salary"].iloc[0] = 0

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
nba.loc[0, "Salary"] = 0
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,0.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Select Multiple Columns from a DataFrame
    * use square brackets with a list of names to extract multiple DataFrame columns.
    * Pandas stores the result in a new DataFrame (a copy)

In [120]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,0.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
nba[["Name", "Team", "Salary"]] # Accesses multiple columns of the DataFrame by passing a list of column names, returning a new DataFrame containing only those columns.

                  Name                Team      Salary
0           Saddiq Bey       Atlanta Hawks         0.0
1    Bogdan Bogdanovic       Atlanta Hawks  18700000.0
2          Kobe Bufkin       Atlanta Hawks   4094244.0
3         Clint Capela       Atlanta Hawks  20616000.0
4       Bruno Fernando       Atlanta Hawks   2581522.0
..                 ...                 ...         ...
587       Ryan Rollins  Washington Wizards   1719864.0
588      Landry Shamet  Washington Wizards  10250000.0
589   Tristan Vukcevic  Washington Wizards         NaN
590       Delon Wright  Washington Wizards   8195122.0
591                NaN                 NaN         NaN

[592 rows x 3 columns]

In [122]:
nba[["Team","Name","Salary"]] # The order of the columns in the resulting DataFrame will be the same as the order of the column names in the list passed to the indexing operator. In this case, the resulting DataFrame will have the columns in the order "Team", "Name", and "Salary".

                   Team               Name      Salary
0         Atlanta Hawks         Saddiq Bey         0.0
1         Atlanta Hawks  Bogdan Bogdanovic  18700000.0
2         Atlanta Hawks        Kobe Bufkin   4094244.0
3         Atlanta Hawks       Clint Capela  20616000.0
4         Atlanta Hawks     Bruno Fernando   2581522.0
..                  ...                ...         ...
587  Washington Wizards       Ryan Rollins   1719864.0
588  Washington Wizards      Landry Shamet  10250000.0
589  Washington Wizards   Tristan Vukcevic         NaN
590  Washington Wizards       Delon Wright   8195122.0
591                 NaN                NaN         NaN

[592 rows x 3 columns]

In [123]:
selected_columns = ["Team", "Name", "Salary"]
nba[selected_columns] # You can also store the list of column names in a variable and pass that variable to the indexing operator to access the desired columns.

                   Team               Name      Salary
0         Atlanta Hawks         Saddiq Bey         0.0
1         Atlanta Hawks  Bogdan Bogdanovic  18700000.0
2         Atlanta Hawks        Kobe Bufkin   4094244.0
3         Atlanta Hawks       Clint Capela  20616000.0
4         Atlanta Hawks     Bruno Fernando   2581522.0
..                  ...                ...         ...
587  Washington Wizards       Ryan Rollins   1719864.0
588  Washington Wizards      Landry Shamet  10250000.0
589  Washington Wizards   Tristan Vukcevic         NaN
590  Washington Wizards       Delon Wright   8195122.0
591                 NaN                NaN         NaN

[592 rows x 3 columns]

## Add New Column to DataFrame
    * use square bracket extraction syntax with an equal sign to add a new Series to a DataFrame.
    * The insert method allows us to insert an element at a specific column index.
    * on the right hand side, we can reference an existing DataFrame column and perform a broadcasting operation on it to create the new Series.

In [124]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,0.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
nba["Sport"] = "Basketball" # Adds a new column "Sport" to the DataFrame and assigns the value "Basketball" to all rows in that column.
nba

,Name,Team,Position,Height,Weight,College,Salary,Sport
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,0.0,Basketball
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,Basketball
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,Basketball
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,Basketball
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,Basketball
...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,Basketball
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,Basketball
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,Basketball
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,Basketball
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basketball

In [126]:
nba = pd.read_csv("data/nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
nba.insert(loc=3, column="Sport", value="Basketball") # Inserts a new column "Sport" at the specified position (index 3) in the DataFrame and assigns the value "Basketball" to all rows in that column.
nba

,Name,Team,Position,Sport,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,Basketball,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,Basketball,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,Basketball,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,Basketball,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,Basketball,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,Basketball,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,Basketball,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,Basketball,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,Basketball,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,Basketball,NaN,NaN,NaN,NaN

In [128]:
nba = pd.read_csv("data/nba.csv")

nba["Salary Doubled"] = nba["Salary"] * 2
nba

,Name,Team,Position,Height,Weight,College,Salary,Salary Doubled
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,9113966.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,37400000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,8188488.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,41232000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,5163044.0
...,...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,3439728.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,20500000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,16390244.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## A Review of the value_counts Method

    * The value_counts method counts the number of times that each unique value occurs in a Series.

In [129]:
nba = pd.read_csv("data/nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
nba["Team"].value_counts()

Team
Dallas Mavericks          23
Denver Nuggets            22
Memphis Grizzlies         22
Miami Heat                22
Milwaukee Bucks           22
Indiana Pacers            21
New York Knicks           21
Oklahoma City Thunder     21
Philadelphia 76ers        21
Toronto Raptors           21
Utah Jazz                 21
Washington Wizards        21
Charlotte Hornets         20
Houston Rockets           20
Phoenix Suns              20
San Antonio Spurs         20
Chicago Bulls             19
Cleveland Cavaliers       19
Detroit Pistons           19
Los Angeles Clippers      19
Los Angeles Lakers        19
Minnesota Timberwolves    19
Atlanta Hawks             18
Boston Celtics            18
Orlando Magic             18
Sacramento Kings          18
Brooklyn Nets             17
Golden State Warriors     17
Portland Trail Blazers    17
New Orleans Pelicans      16
Name: count, dtype: int64

In [131]:
nba["Position"].value_counts(normalize=True) * 100 # Returns the relative frequencies of each unique value in the "Position" column as percentages. The value_counts() method with the normalize=True argument calculates the relative frequencies, and multiplying by 100 converts them to percentages.

Position
G      39.212329
F      32.020548
C       8.047945
G-F     7.876712
F-C     6.335616
C-F     3.938356
F-G     2.568493
Name: proportion, dtype: float64

In [132]:
nba["Salary"].value_counts(bins=5) # Returns the count of values in the "Salary" column, grouped into 5 equal-width bins. The value_counts() method with the bins argument groups the values into specified bins and counts the number of occurrences in each bin.

(457484.275, 10790235.8]    355
(10790235.8, 21071580.6]     66
(31352925.4, 41634270.2]     29
(21071580.6, 31352925.4]     26
(41634270.2, 51915615.0]     12
Name: count, dtype: int64

## Drop DataFrame Rows with Missing Values
    * Pandas uses a NaN designation for cells that have a missing value.
    * The dropna method deletes rows with missing values. Its default behaviour is to remove a row if it has any missing values.
    * Pass the how parameter an argument of "all" to delete rows where all the values are NaN.
    * The subset parameters customizes/limits the columns that pandas will use to drop rows with missing values.

In [133]:
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
nba.dropna() # by default, it will drop rows where any column has a missing value (NaN). If you want to drop columns instead, you can use the axis parameter and set it to 1 (axis=1) or 'columns' (axis='columns').

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [135]:
nba.dropna(how="any") # Drops rows where any column has a missing value (NaN). This is the default behavior of dropna().

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [136]:
nba.dropna(how="all") # Drops rows where all columns have missing values (NaN). The how parameter with the value "all" specifies that only rows where all values are NaN should be dropped.

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [137]:
nba.dropna(subset=["College"]) # Drops rows where the "College" column has missing values (NaN). The subset parameter specifies that only the "College" column should be considered when determining which rows to drop based on missing values.

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [138]:
nba.dropna(subset=["College", "Salary"]) # Drops rows where the "College" or "Salary" column has a missing value (NaN). The subset parameter specifies that only the "College" and "Salary" columns should be considered when determining which rows to drop based on missing values.

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
585,Eugene Omoruyi,Washington Wizards,F,6-6,235.0,Oregon,559782.0
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [139]:
nba.dropna(subset=["College", "Salary"], how="all") # drop the row only when both "College" and "Salary" columns have missing values (NaN).
# Drops rows where the "College" or "Salary" column has a missing value (NaN). 
# The subset parameter specifies that only the "College" and "Salary" columns should be considered when determining which rows to drop based on missing values. 
# The how parameter with the value "all" specifies that only rows where all values in the specified subset are NaN should be dropped.

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

## Fill in Missing Values with the fillna Method
    * the fillna method replaces missing NaN values with its argument.
    * the fillna method is available on both DataFrame and Series.
    * an extracted Series is a view of the original DataFrame, but the fillna method returns a copy.

In [140]:
nba.dropna(how="all", inplace=True)
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [141]:
nba.fillna({"Salary": 0}) # Fills missing values (NaN) in the "Salary" column with the value 0. 
# The fillna() method is used to replace missing values in a DataFrame, and by specifying the column name and the value to fill, it will only fill the missing values in that specific column.

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

## The astype() Method
    * the astype() converts a Series's values to a specified type.
    * pass in the specified type as either a string or the core Python data type.
    * Pandas cannot convert NaN values to numeric types, so we need to eliminate/replace them before we perform the conversion.
    * the dtypes attribute returns a Series with the DataFrame's columns and their types.

    * the category type is ideal for columns with a limited number of unique values.
    * the nunique method will return a Series with the number of unique values in each column.
    * with categories, pandas does not create a separate value in memory for each 'cell'. Rather the cell's point to a single copy for each unique value.

In [142]:
nba
# whenever pandas import a CSV file, it will automatically convert empty cells to NaN (Not a Number) to represent missing values. 
# Also, as long as there is a NaN value in a column, the column will be converted to a float data type, even if the other values in the column are integers. 
# This is because NaN is a special floating-point value, and pandas promotes the entire column to a float data type to accommodate the presence of NaN values.
# This allows for easier handling of missing data in the DataFrame, as you can use methods like dropna() and fillna() to manage those missing values effectively.

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [143]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [144]:
nba['Salary'] = nba['Salary'].astype("Int64") 
# Converts the "Salary" column to the nullable integer data type "Int64". 
# This allows for the presence of missing values (NaN) while still treating the column as integers. The "Int64" data type is a special pandas extension type 
# that can handle missing values without converting the entire column to a float data type.

nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,<NA>
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122

In [145]:
nba.dtypes

Name            str
Team            str
Position        str
Height          str
Weight      float64
College         str
Salary        Int64
dtype: object

In [146]:
nba['Weight'] = nba['Weight'].fillna(0).astype(int) 
# To convert a type, none of the column values can be NaN.
# Fills missing values (NaN) in the "Weight" column with 0 and then converts the column to the integer data type. 
# This allows for the presence of missing values (NaN) while still treating the column as integers. The fillna(0) method replaces NaN values with 0, 
# and then astype(int) converts the entire column to integers.

In [147]:
nba.dtypes

Name          str
Team          str
Position      str
Height        str
Weight      int64
College       str
Salary      Int64
dtype: object

In [148]:
nba['Team'].value_counts()

Team
Dallas Mavericks          23
Denver Nuggets            22
Memphis Grizzlies         22
Miami Heat                22
Milwaukee Bucks           22
Indiana Pacers            21
New York Knicks           21
Oklahoma City Thunder     21
Philadelphia 76ers        21
Toronto Raptors           21
Utah Jazz                 21
Washington Wizards        21
Charlotte Hornets         20
Houston Rockets           20
Phoenix Suns              20
San Antonio Spurs         20
Chicago Bulls             19
Cleveland Cavaliers       19
Detroit Pistons           19
Los Angeles Clippers      19
Los Angeles Lakers        19
Minnesota Timberwolves    19
Atlanta Hawks             18
Boston Celtics            18
Orlando Magic             18
Sacramento Kings          18
Brooklyn Nets             17
Golden State Warriors     17
Portland Trail Blazers    17
New Orleans Pelicans      16
Name: count, dtype: int64

In [149]:
nba['Team'].nunique() # Returns the number of unique values in the "Team" column. The nunique() method counts the number of distinct values in a Series or DataFrame column.

30

In [150]:
nba.nunique() # Returns the number of unique values in each column of the DataFrame. The nunique() method counts the number of distinct values in each column and returns a Series with the counts for each column.

Name        591
Team         30
Position      7
Height       20
Weight       94
College     182
Salary      298
dtype: int64

In [151]:
nba.info()

<class 'pandas.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    str
 1   Team      591 non-null    str
 2   Position  584 non-null    str
 3   Height    585 non-null    str
 4   Weight    591 non-null    int64
 5   College   578 non-null    str
 6   Salary    488 non-null    Int64
dtypes: Int64(1), int64(1), str(5)
memory usage: 33.0 KB

In [152]:
nba['Position'] = nba['Position'].astype("category") # Converts the "Position" column to the categorical data type. This can be useful for columns that have a limited number of unique values, as it can save memory and improve performance when performing operations on that column.
nba.dtypes

Name             str
Team             str
Position    category
Height           str
Weight         int64
College          str
Salary         Int64
dtype: object

In [153]:
nba['Team'] = nba['Team'].astype("category")
# Converts the "Team" column to the categorical data type "category".

nba.dtypes

Name             str
Team        category
Position    category
Height           str
Weight         int64
College          str
Salary         Int64
dtype: object

In [154]:
nba.info() # note the memory usage has decreased significantly after converting the "Position" and "Team" columns to the categorical data type.

<class 'pandas.DataFrame'>
RangeIndex: 591 entries, 0 to 590
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      591 non-null    str
 1   Team      591 non-null    category
 2   Position  584 non-null    category
 3   Height    585 non-null    str
 4   Weight    591 non-null    int64
 5   College   578 non-null    str
 6   Salary    488 non-null    Int64
dtypes: Int64(1), category(2), int64(1), str(3)
memory usage: 25.2 KB

## Sort a DataFrame with the sort_values() Method
    * the sort_values method sorts a DataFrame by the values in one or more columns. The default is in ascending order.
    * the first parameter 'by' expects the column(s) to sort by.
    * if sorting by a single column, pass a string with the column name.
    * the ascending parameter specify the sort order.
    * the na_position parameter customizes where pandas places NaN value.

    * to sort multiple columns, pass the by parameter a list of column names. Pandas will sort in the specified column order (first to last).
    * pass the ascending parameter a boolean to sort all columns in a consistent order (all ascending or all descending).
    * pass ascending a list of customize sort order per column. the ascending list length must match the by list.

In [155]:
nba = pd.read_csv("data/nba.csv")
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [156]:
nba['Name'].sort_values() # Sorts the values in the "Name" column in ascending order. The sort_values() method sorts the values in a Series or DataFrame column and returns a new Series with the sorted values.

122        A.J. Lawson
324           AJ Green
6           AJ Griffin
141       Aaron Gordon
198      Aaron Holiday
            ...
83         Zach LaVine
149         Zeke Nnaji
291    Ziaire Williams
370    Zion Williamson
591                NaN
Name: Name, Length: 592, dtype: str

In [157]:
nba['Name'].sort_values(ascending=False) # Sorts the values in the "Name" column in descending order. The sort_values() method with the ascending=False argument sorts the values in descending order and returns a new Series with the sorted values.

370    Zion Williamson
291    Ziaire Williams
149         Zeke Nnaji
83         Zach LaVine
515       Zach Collins
            ...
141       Aaron Gordon
6           AJ Griffin
324           AJ Green
122        A.J. Lawson
591                NaN
Name: Name, Length: 592, dtype: str

In [158]:
nba['Salary'].sort_values() # Sorts the values in the "Salary" column in ascending order. The sort_values() method sorts the values in a Series or DataFrame column and returns a new Series with the sorted values.

5      508891.0
22     559782.0
55     559782.0
52     559782.0
585    559782.0
         ...
547         NaN
578         NaN
584         NaN
589         NaN
591         NaN
Name: Salary, Length: 592, dtype: float64

In [159]:
nba['Salary'].sort_values(na_position="first") # Sorts the values in the "Salary" column in ascending order, placing any missing values (NaN) at the beginning of the sorted output. The na_position parameter with the value "first" specifies that NaN values should be placed at the beginning of the sorted output.

23            NaN
26            NaN
28            NaN
35            NaN
39            NaN
          ...
261    47607350.0
145    47607350.0
436    47607350.0
461    47649433.0
175    51915615.0
Name: Salary, Length: 592, dtype: float64

In [160]:
nba[["Name", "Salary"]].sort_values(by="Salary") # Sorts the DataFrame by the "Salary" column in ascending order, returning a new DataFrame with the sorted values. The sort_values() method with the by argument specifies which column to sort by.

                 Name    Salary
5       Trent Forrest  508891.0
22         JD Davison  559782.0
55        Leaky Black  559782.0
52       Jalen Wilson  559782.0
585    Eugene Omoruyi  559782.0
..                ...       ...
547    Gary Trent Jr.       NaN
578        Taj Gibson       NaN
584     Kendrick Nunn       NaN
589  Tristan Vukcevic       NaN
591               NaN       NaN

[592 rows x 2 columns]

In [161]:
nba[["Name", "Salary"]].sort_values(by="Name", ascending=False) # Sorts the DataFrame by the "Name" column in descending order, returning a new DataFrame with the sorted values. The sort_values() method with the by argument specifies which column to sort by, and the ascending=False argument sorts the values in descending order.

                Name      Salary
370  Zion Williamson  34005250.0
291  Ziaire Williams   4810200.0
149       Zeke Nnaji   4306281.0
83       Zach LaVine  40064220.0
515     Zach Collins   7700000.0
..               ...         ...
141     Aaron Gordon  22266182.0
6         AJ Griffin   3712920.0
324         AJ Green   1901769.0
122      A.J. Lawson         NaN
591              NaN         NaN

[592 rows x 2 columns]

In [162]:
nba[["Name", "Salary"]].sort_values(by="Salary", ascending=False) # Sorts the DataFrame by the "Salary" column in descending order, returning a new DataFrame with the sorted values. The sort_values() method with the by argument specifies which column to sort by, and the ascending=False argument sorts the values in descending order.

                 Name      Salary
175     Stephen Curry  51915615.0
461      Kevin Durant  47649433.0
261      LeBron James  47607350.0
436       Joel Embiid  47607350.0
145      Nikola Jokic  47607350.0
..                ...         ...
547    Gary Trent Jr.         NaN
578        Taj Gibson         NaN
584     Kendrick Nunn         NaN
589  Tristan Vukcevic         NaN
591               NaN         NaN

[592 rows x 2 columns]

In [163]:
nba[["Position", "Salary"]].sort_values(by=["Position","Salary"])

    Position     Salary
143        C   559782.0
252        C   559782.0
343        C   559782.0
406        C   559782.0
473        C   559782.0
..       ...        ...
138      NaN  1119563.0
299      NaN  1119563.0
541      NaN  1119563.0
564      NaN  1119563.0
591      NaN        NaN

[592 rows x 2 columns]

In [164]:
nba[["Position", "Salary"]].sort_values(by=["Position","Salary"], ascending=[True, False]) # Sorts the DataFrame first by the "Position" column in ascending order and then by the "Salary" column in descending order. The sort_values() method with the by argument specifies which columns to sort by, and the ascending argument with a list of boolean values specifies the sorting order for each column.

    Position      Salary
145        C  47607350.0
344        C  41000000.0
453        C  32459438.0
329        C  25000000.0
3          C  20616000.0
..       ...         ...
299      NaN   1119563.0
541      NaN   1119563.0
564      NaN   1119563.0
15       NaN    559782.0
591      NaN         NaN

[592 rows x 2 columns]

## Sort DataFrame with the sort_index() method
    * the sort_index method sorts the DataFrame by its index position/labels.

In [165]:
nba = nba.sort_values(["Team", "Name"]) # Sorts the DataFrame first by the "Team" column in ascending order and then by the "Name" column in ascending order. The sort_values() method with a list of column names sorts the DataFrame by those columns in the specified order.
nba

,Name,Team,Position,Height,Weight,College,Salary
6,AJ Griffin,Atlanta Hawks,F,6-6,220.0,Duke,3712920.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
8,De'Andre Hunter,Atlanta Hawks,F-G,6-8,221.0,Virginia,20089286.0
...,...,...,...,...,...,...,...
578,Taj Gibson,Washington Wizards,F,6-9,232.0,Southern California,NaN
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
580,Tyus Jones,Washington Wizards,G,6-2,196.0,Duke,14000000.0
573,Xavier Cooks,Washington Wizards,F,6-8,183.0,Winthrop,1719864.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
nba.sort_index()

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
nba.sort_index(ascending=False) # Sorts the DataFrame by its index in descending order. The sort_index() method with the ascending=False argument sorts the index in descending order and returns a new DataFrame with the sorted index.

,Name,Team,Position,Height,Weight,College,Salary
591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,NaN
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
...,...,...,...,...,...,...,...
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0

## Sort DataFrame with the rank() Method
    * the rank() method assigns a numeric ranking to each Series value.
    * Pandas will assign the same rank to equal values and create a 'gap' in the dataset for the ranks.

In [173]:
nba = pd.read_csv("data/nba.csv").dropna(how="all") # Reads the CSV file and drops rows where all columns have missing values (NaN). The dropna() method with the how="all" argument specifies that only rows where all values are NaN should be dropped.
nba = nba.fillna(0)
nba

,Name,Team,Position,Height,Weight,College,Salary
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0
...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0

In [175]:
nba["Salary"].rank() # Returns the rank of each value in the DataFrame, with the default method of ranking being "average". The rank() method assigns ranks to values in a Series or DataFrame column, with the option to specify different ranking methods.

0      361.0
1      512.0
2      349.0
3      523.0
4      284.0
       ...
586    544.0
587    197.5
588    452.0
589     52.0
590    429.0
Name: Salary, Length: 591, dtype: float64

In [176]:
nba["Salary"].rank(ascending=False) .astype(int) # Returns the rank of each value in the "Salary" column in descending order, and then converts the ranks to integers. The rank() method with the ascending=False argument assigns ranks in descending order, and the astype(int) method converts the resulting ranks to integers.

0      231
1       80
2      243
3       69
4      308
      ...
586     48
587    394
588    140
589    540
590    163
Name: Salary, Length: 591, dtype: int64

In [177]:
nba["Salary Rank"] = nba["Salary"].rank(ascending=False).astype(int) # Adds a new column "Salary Rank" to the DataFrame, which contains the rank of each value in the "Salary" column in descending order, with the ranks converted to integers. The rank() method with the ascending=False argument assigns ranks in descending order, and the astype(int) method converts the resulting ranks to integers.
nba

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
0,Saddiq Bey,Atlanta Hawks,F,6-7,215.0,Villanova,4556983.0,231
1,Bogdan Bogdanovic,Atlanta Hawks,G,6-5,225.0,Fenerbahce,18700000.0,80
2,Kobe Bufkin,Atlanta Hawks,G,6-5,195.0,Michigan,4094244.0,243
3,Clint Capela,Atlanta Hawks,C,6-10,256.0,Elan Chalon,20616000.0,69
4,Bruno Fernando,Atlanta Hawks,F-C,6-10,240.0,Maryland,2581522.0,308
...,...,...,...,...,...,...,...,...
586,Jordan Poole,Washington Wizards,G,6-4,194.0,Michigan,27955357.0,48
587,Ryan Rollins,Washington Wizards,G,6-3,180.0,Toledo,1719864.0,394
588,Landry Shamet,Washington Wizards,G,6-4,190.0,Wichita State,10250000.0,140
589,Tristan Vukcevic,Washington Wizards,F,6-10,220.0,Real Madrid,0.0,540
590,Delon Wright,Washington Wizards,G,6-5,185.0,Utah,8195122.0,163

In [178]:
nba.sort_values(by="Salary", ascending=False) # Sorts the DataFrame by the "Salary" column in descending order, returning a new DataFrame with the sorted values. The sort_values() method with the by argument specifies which column to sort by, and the ascending=False argument sorts the values in descending order.

,Name,Team,Position,Height,Weight,College,Salary,Salary Rank
175,Stephen Curry,Golden State Warriors,G,6-2,185.0,Davidson,51915615.0,1
461,Kevin Durant,Phoenix Suns,F,6-10,240.0,Texas,47649433.0,2
145,Nikola Jokic,Denver Nuggets,C,6-11,284.0,Mega Basket,47607350.0,4
436,Joel Embiid,Philadelphia 76ers,C-F,7-0,280.0,Kansas,47607350.0,4
261,LeBron James,Los Angeles Lakers,F,6-9,250.0,St. Vincent-St. Mary HS (OH),47607350.0,4
...,...,...,...,...,...,...,...,...
547,Gary Trent Jr.,Toronto Raptors,G-F,6-5,209.0,Duke,0.0,540
23,Blake Griffin,Boston Celtics,F,6-9,250.0,Oklahoma,0.0,540
26,Mfiondu Kabengele,Boston Celtics,C,6-10,250.0,Florida State,0.0,540
28,Svi Mykhailiuk,Boston Celtics,G-F,6-7,205.0,Kansas,0.0,540
35,Robert Williams III,Boston Celtics,C-F,6-9,237.0,Texas A&M,0.0,540