## Data Types Conversion for Memory Optimization
    * the pd.to_datetime method converts a Series to hold datetime values.
    * the format parameter informs pandas of the format that the times are stored in.
    * we pass symbols designating the segments of the string. e.g. %m means 'month' and %d means 'day'.
    * the dt attribute reveals an object with many datetime related attributes and methods.
    * the dt.time attribute extracts only the time from each value in a datetime Series.
    * use the astype method to convert the values in a Series to another type.
    * the parse_dates parameter of read_csv is an alternate way to parse strings as datetimes.

In [2]:
import pandas as pd

employees = pd.read_csv('data/employees.csv')
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    str
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   str
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 62.6+ KB

In [3]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [4]:
# Convert the "Start Date" column to datetime format
employees["Start Date"] = pd.to_datetime(employees['Start Date'], format='%m/%d/%Y') 
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39 PM,96914,1.421,False,Product
998,Larry,Male,2013-04-20,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,6:24 PM,129949,10.169,True,Sales

In [5]:
# Convert the "Last Login Time" column to datetime format (time only)
employees["Last Login Time"] = pd.to_datetime(employees['Last Login Time'], format='%I:%M %p').dt.time
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [6]:
# Convert the "Senior Management" column to boolean type
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [7]:
# Convert the Gender column to category type
employees["Gender"] = employees["Gender"].astype('category')
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[us]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    str
dtypes: bool(1), category(1), datetime64[us](1), float64(1), int64(1), object(1), str(2)
memory usage: 49.0+ KB

In [8]:
# alternatively, we can specify the data types when reading the CSV file
employees = pd.read_csv('data/employees.csv', parse_dates=['Start Date'], dtype={'Gender': 'category'})
employees["Last Login Time"] = pd.to_datetime(employees['Last Login Time'], format='%I:%M %p').dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[us]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    str
dtypes: bool(1), category(1), datetime64[us](1), float64(1), int64(1), object(1), str(2)
memory usage: 49.1+ KB

In [9]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

## Filter a DataFrame Based on Condition
    * Pandas needs a Series of Booleans to perform filtering.
    * Pass the Boolean Series inside square brackets after the DataFrame.
    * we can generate a Boolean Series using a wide variety of operation (equality, inequality, less than, greater than, etc)

In [10]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [11]:
# Filtering for Male employees
male_employees = employees[employees["Gender"] == 'Male'] 
male_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,17:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [12]:
# Filtering for Finance department employees
finance_employees = employees[employees["Team"] == 'Finance']
finance_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,22:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,16:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [13]:
# Filtering for Senior Management employees
senior_management_employees = employees[employees["Senior Management"]]
senior_management_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,15:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,17:47:00,98874,4.479,True,Marketing
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [14]:
# Filtering for employees with Salary greater than $110,000
high_salary_employees = employees[employees["Salary"] > 110000]
high_salary_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
...,...,...,...,...,...,...,...,...
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [15]:
# Filtering for employees with less than 1.5% Bonus
low_bonus_employees = employees[employees["Bonus %"] < 1.5]
low_bonus_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
58,Theresa,Female,2010-04-11,07:18:00,72670,1.481,True,Engineering
77,Charles,Male,2004-09-14,20:13:00,107391,1.260,True,Marketing
175,Willie,Male,1998-02-17,20:20:00,146651,1.451,True,Engineering
189,Clarence,Male,1998-05-02,03:16:00,85700,1.215,False,Sales
217,Douglas,Male,1999-09-03,16:00:00,83341,1.015,True,Client Services
273,Nicholas,Male,1994-04-12,20:21:00,74669,1.113,True,Product
279,Ruby,Female,2000-11-08,19:35:00,105946,1.139,False,Business Development
365,Gloria,NaN,1983-07-19,01:57:00,140885,1.113,False,Human Resources
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
527,Helen,NaN,1993-12-02,13:42:00,45724,1.022,False,Product
570,Kelly,Female,1996-08-16,03:09:00,41427,1.431,False,Product
578,Amanda,Female,1982-03-17,23:46:00,107111,1.438,True,Product
579,Harold,Male,2010-10-18,20:45:00,65673,1.187,True,Legal
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
618,Peter,Male,1992-11-24,17:43:00,69297,1.268,False,Finance
638,Frances,Female,1996-11-12,18:08:00,112467,1.433,False,Business Development
652,Willie,Male,2009-12-05,05:39:00,141932,1.017,True,Engineering
708,Steve,Male,2002-01-11,21:17:00,51821,1.197,True,Legal
732,Henry,Male,1986-05-12,02:04:00,59943,1.432,False,Finance
734,NaN,Female,1994-12-18,20:42:00,138807,1.400,True,Human Resources
746,Gloria,Female,2004-08-19,10:31:00,46602,1.027,True,Business Development
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
929,Theresa,Female,2001-04-27,21:17:00,75661,1.079,True,Legal
954,Joe,Male,1980-01-19,16:06:00,119667,1.148,True,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product

In [16]:
# Employees that started before 1985
early_start_employees = employees[employees["Start Date"] < "1985-01-01"]
early_start_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
28,Terry,Male,1981-11-27,18:30:00,124008,13.464,True,Client Services
37,Linda,Female,1981-10-19,20:49:00,57427,9.557,True,Client Services
...,...,...,...,...,...,...,...,...
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,22:35:00,146907,11.738,False,Engineering
985,Stephen,NaN,1983-07-10,20:10:00,85668,1.909,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [17]:
import datetime as dt

# Employees that logged in before noon
morning_login_employees = employees[employees["Last Login Time"] < dt.time(12, 0)]
morning_login_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
...,...,...,...,...,...,...,...,...
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

## Filter with More than One Condition (AND - &)
    * add the & operator in between two boolean Series to filter by multiple conditions.
    * we can assign the Series to variables to make the syntax more readable.

In [18]:
# female employees who work in Marketing
is_female = employees["Gender"] == 'Female'
is_marketing = employees["Team"] == 'Marketing'
female_marketing_employees = employees[ is_female & is_marketing]
female_marketing_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
43,Marilyn,Female,1980-12-07,03:16:00,73524,5.207,True,Marketing
62,NaN,Female,2007-06-12,17:25:00,58112,19.414,True,Marketing
98,Tina,Female,2016-06-16,19:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,13:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,20:45:00,114412,8.756,True,Marketing
201,Kimberly,Female,1997-07-15,05:57:00,36643,7.953,False,Marketing
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
305,Margaret,Female,1993-02-06,13:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,15:01:00,145988,18.243,False,Marketing
331,Evelyn,Female,1983-09-03,13:58:00,36759,17.269,True,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
446,Cheryl,Female,1994-08-16,08:33:00,67150,15.850,True,Marketing
468,Janice,Female,1997-06-28,13:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,13:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,21:10:00,123649,10.154,True,Marketing
535,Louise,Female,1981-09-18,05:47:00,91462,8.205,False,Marketing
568,Susan,Female,1986-04-18,09:31:00,90829,19.142,False,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
586,Rose,Female,2004-10-30,16:34:00,56961,7.585,False,Marketing
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
625,Cynthia,Female,2015-06-29,06:38:00,82408,8.701,True,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
629,Debra,Female,1983-03-12,12:19:00,74911,19.513,False,Marketing
656,Lisa,Female,1982-02-09,18:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,18:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
730,Nicole,Female,2009-04-26,00:40:00,66047,18.674,True,Marketing
785,NaN,Female,1982-07-24,00:00:00,57811,8.941,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
817,Ruby,Female,2008-05-31,20:41:00,83112,4.083,False,Marketing
824,Julia,Female,2014-08-18,03:12:00,97566,2.147,False,Marketing
881,Ruby,Female,1980-01-28,23:08:00,142868,6.318,False,Marketing
883,Kathryn,Female,1995-10-27,15:39:00,57300,18.015,False,Marketing
894,Betty,Female,2002-11-19,10:40:00,37005,7.645,True,Marketing
913,Lois,Female,2015-12-11,16:10:00,99747,6.168,False,Marketing
930,Nancy,Female,2001-09-10,23:57:00,85213,2.386,True,Marketing
942,Lori,Female,2015-11-20,13:15:00,75498,6.537,True,Marketing
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

In [19]:
# female employees who work in Marketing who earn more than $100,000
is_high_earning = employees["Salary"] > 100000
female_high_earning_marketing_employees = employees[is_female & is_marketing & is_high_earning]
female_high_earning_marketing_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,19:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,13:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,20:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,13:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,15:01:00,145988,18.243,False,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
468,Janice,Female,1997-06-28,13:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,13:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,21:10:00,123649,10.154,True,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
656,Lisa,Female,1982-02-09,18:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,18:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
881,Ruby,Female,1980-01-28,23:08:00,142868,6.318,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

## Filter with More than One Condition ( OR  - | )
    * use the | operator in between two boolean Series to filter by either condition

In [20]:
# Employees who are either Senior Management or started before 1990
is_senior_management = employees["Senior Management"]
started_before_1990 = employees["Start Date"] < "1990-01-01"
senior_or_early_employees = employees[is_senior_management | started_before_1990]
senior_or_early_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,15:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,17:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [21]:
# employees whose First Name is 'Robert' who work in Client Services or Started after 2016-06-01
is_named_robert = employees["First Name"] == 'Robert'
is_client_services = employees["Team"] == 'Client Services'
started_after_june_2016 = employees["Start Date"] > "2016-06-01"
robert_client_services_or_recent_employees = employees[(is_named_robert & is_client_services) | started_after_june_2016]
robert_client_services_or_recent_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
98,Tina,Female,2016-06-16,19:47:00,100705,16.961,True,Marketing
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services
451,Terry,NaN,2016-07-15,00:29:00,140002,19.490,True,Marketing

## The isin() Method
    * the isin() Series method accepts a collection object like a list, tuple, or Series.
    * the method returns True for a row if its value is found in the collection.

In [22]:
# employees who are on Legal team or in Sales team or in Product team
is_legal = employees["Team"] == 'Legal'
is_sales = employees["Team"] == 'Sales'
is_product = employees["Team"] == 'Product'
legal_sales_or_product_employees = employees[is_legal | is_sales | is_product]
legal_sales_or_product_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,15:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,23:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,17:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,20:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,16:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [23]:
is_legal_sales_or_product_employees = employees["Team"].isin(['Legal', 'Sales', 'Product'])
legal_sales_or_product_employees = employees[is_legal_sales_or_product_employees]
legal_sales_or_product_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,15:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,23:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,17:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,20:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,16:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

## The isnull and notnull Methods
    * the isnull method returns True for NaN values in a Series
    * the notnull method returns True for present values in a Series

In [24]:
# employees with missing or null Team information
missing_team_employees = employees[employees["Team"].isnull()]
missing_team_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
23,NaN,Male,2012-06-14,16:19:00,125792,5.042,True,NaN
32,NaN,Male,1998-08-21,14:27:00,122340,6.417,True,NaN
91,James,NaN,2005-01-26,23:00:00,128771,8.309,False,NaN
109,Christopher,Male,2000-04-22,10:15:00,37919,11.449,False,NaN
139,NaN,Female,1990-10-03,01:08:00,132373,10.527,True,NaN
199,Jonathan,Male,2009-07-17,08:15:00,130581,16.736,True,NaN
258,Michael,Male,2002-01-24,03:04:00,43586,12.659,False,NaN
290,Jeremy,Male,1988-06-14,18:20:00,129460,13.657,True,NaN
314,Bobby,Male,1996-03-31,17:40:00,112117,6.338,False,NaN
367,Edward,Male,1989-08-04,06:06:00,66067,10.957,True,NaN
382,NaN,Female,1996-04-18,15:57:00,107024,12.182,True,NaN
434,Joyce,Female,1995-02-07,07:38:00,50701,14.227,True,NaN
438,Jason,Male,1998-11-20,14:54:00,69244,6.220,True,NaN
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
479,Richard,Male,1997-07-04,11:47:00,47647,18.787,True,NaN
512,Wanda,Female,1993-04-06,03:11:00,78883,19.695,False,NaN
513,Jimmy,Male,2013-11-19,19:29:00,63549,19.624,False,NaN
520,Peter,Male,2003-02-22,09:09:00,56580,8.411,True,NaN
567,NaN,Female,1980-04-01,20:04:00,48141,12.605,True,NaN
573,Kimberly,Female,1981-12-30,04:51:00,81800,5.435,True,NaN
580,Harry,Male,1985-01-27,20:18:00,65482,18.089,False,NaN
626,NaN,Female,1997-04-13,08:03:00,131755,2.930,True,NaN
634,Carl,Male,1987-03-30,17:59:00,75598,19.289,False,NaN
635,Randy,Male,2000-09-27,03:04:00,89831,13.047,True,NaN
647,Donald,Male,1988-04-06,10:00:00,122920,5.320,False,NaN
669,Joseph,NaN,1982-03-28,13:05:00,86564,11.879,True,NaN
684,Alice,Female,2016-01-21,17:07:00,117787,10.485,False,NaN
706,Todd,Male,1993-07-04,18:53:00,128175,18.473,True,NaN
726,Daniel,Male,2016-02-29,04:04:00,77287,13.000,True,NaN
753,Antonio,Male,1999-06-06,22:54:00,41928,5.478,True,NaN
774,NaN,Female,2000-06-18,07:36:00,106428,10.867,True,NaN
781,Lawrence,Male,1995-07-03,22:55:00,46378,9.127,False,NaN
794,Nicole,Female,2004-03-01,17:17:00,44021,10.286,False,NaN
826,NaN,NaN,1988-08-01,01:35:00,87103,5.665,True,NaN
850,Charles,Male,1997-09-03,10:04:00,148291,6.002,False,NaN
851,Bobby,Male,1996-08-19,01:16:00,147842,16.158,True,NaN
853,Mildred,Female,2007-04-06,22:06:00,139284,11.390,True,NaN
855,Phillip,NaN,2003-10-20,11:09:00,89700,2.277,True,NaN
864,Ryan,Male,2012-11-16,13:47:00,57292,6.010,False,NaN
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN

In [25]:
# employees who are not null in the Team column
non_null_team_employees = employees[employees["Team"].notnull()]
non_null_team_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

## The between Method
    * the between method returns True if a Series value is found within its range

In [26]:
# employees whose salary is between $90,000 and $120,000
is_salary_between_90k_and_120k = employees["Salary"].between(90000, 120000)
salary_between_90k_and_120k_employees = employees[is_salary_between_90k_and_120k]
salary_between_90k_and_120k_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
11,Julie,Female,1997-10-26,15:19:00,102508,12.637,True,Legal
...,...,...,...,...,...,...,...,...
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
990,Robin,Female,1987-07-24,13:35:00,100765,10.982,True,Client Services
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
994,George,Male,2013-06-21,17:47:00,98874,4.479,True,Marketing
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product

In [27]:
# employees started between 1980 and 1990
is_started_between_1980_and_1990 = employees["Start Date"].between("1980-01-01", "1990-12-31")
started_between_1980_and_1990_employees = employees[is_started_between_1980_and_1990]
started_between_1980_and_1990_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
17,Shawn,Male,1986-12-07,19:45:00,111737,6.414,False,Product
...,...,...,...,...,...,...,...,...
983,John,Male,1982-12-23,22:35:00,146907,11.738,False,Engineering
985,Stephen,NaN,1983-07-10,20:10:00,85668,1.909,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
990,Robin,Female,1987-07-24,13:35:00,100765,10.982,True,Client Services
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [28]:
# employees who login in between 9:00 AM and 5:00 PM
is_login_between_9_and_5 = employees["Last Login Time"].between(dt.time(9, 0), dt.time(17, 0))
login_between_9_and_5_employees = employees[is_login_between_9_and_5]
login_between_9_and_5_employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
989,Justin,NaN,1991-02-10,16:58:00,38344,3.794,False,Legal
990,Robin,Female,1987-07-24,13:35:00,100765,10.982,True,Client Services
993,Tina,Female,1997-05-15,15:53:00,56450,19.040,True,Engineering
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development

## The duplicated Method
    * the duplicated method returns True if a Series value is a duplicate.
    * Pandas will mark one occurance of a repeated value as a non-duplicate.
    * use the keep parameter to designate whether the first or last occurance of a repeated value should be considered the 'non-duplicate'.
    * pass False to the keep parameter to mark all occurances of repeated values as duplicates.
    * use the tilde symbol ~ to invert a Series's values. Trues will become Falses, and vice versa.

In [29]:
# employees with duplicated First Name.
duplicated_first_names = employees[employees.duplicated(subset=["First Name"], keep=False)]
duplicated_first_names

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [30]:
duplicated_first_names = employees[employees.duplicated(subset=["First Name"], keep='first')]
duplicated_first_names

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
23,NaN,Male,2012-06-14,16:19:00,125792,5.042,True,NaN
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
32,NaN,Male,1998-08-21,14:27:00,122340,6.417,True,NaN
34,Jerry,Male,2004-01-10,12:56:00,95734,19.096,False,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [31]:
duplicated_first_names = employees[employees.duplicated(subset=["First Name"], keep='last')]
duplicated_first_names

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
959,Albert,Male,1992-09-19,02:35:00,45094,5.850,True,Business Development
960,Stephen,Male,1989-10-29,23:34:00,93997,18.093,True,Business Development
970,Alice,Female,1988-09-03,20:54:00,63571,15.397,True,Product
973,Russell,Male,2013-05-10,23:08:00,137359,11.105,False,Business Development
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources

In [32]:
# inverse of duplicated: employees with unique First Name
duplicated_first_names = employees[~employees.duplicated(subset=["First Name"], keep=False)]
duplicated_first_names

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,22:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,15:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

## The drop_duplicates Method
    * the drop_duplicates method deletes rows with duplicate values.
    * by default, it will remove a row if all of its values are shared with another row.
    * the subset parameter configures the columns to look for duplicate values within.
    * pass a list to subset parameter to look for duplicates across multiple columns.

In [33]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [34]:
employees.drop_duplicates()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [35]:
employees.drop_duplicates(subset=["Team"])

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
13,Gary,Male,2008-01-27,23:40:00,109831,5.831,False,Sales
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution

In [36]:
employees.drop_duplicates(subset=["Team"], keep='first')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
13,Gary,Male,2008-01-27,23:40:00,109831,5.831,False,Sales
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution

In [37]:
employees.drop_duplicates(subset=["Team"], keep='last')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
989,Justin,NaN,1991-02-10,16:58:00,38344,3.794,False,Legal
990,Robin,Female,1987-07-24,13:35:00,100765,10.982,True,Client Services
993,Tina,Female,1997-05-15,15:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,17:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,16:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,18:24:00,129949,10.169,True,Sales

In [38]:
employees.drop_duplicates(subset=["Team"], keep=False)

Empty DataFrame
Columns: [First Name, Gender, Start Date, Last Login Time, Salary, Bonus %, Senior Management, Team]
Index: []

In [40]:
employees.drop_duplicates(subset=["First Name"], keep=False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,22:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,15:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

In [41]:
employees.drop_duplicates(subset=["Senior Management","Team"])

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
11,Julie,Female,1997-10-26,15:19:00,102508,12.637,True,Legal
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
13,Gary,Male,2008-01-27,23:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
16,Jeremy,Male,2010-09-21,05:56:00,90370,7.369,False,Human Resources
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
21,Matthew,Male,1995-09-05,02:12:00,100612,13.645,False,Marketing
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution
45,Roger,Male,1980-04-17,11:32:00,88010,13.886,True,Sales
54,Sara,Female,2007-08-15,09:23:00,83677,8.999,False,Engineering
60,Paula,NaN,2005-11-23,14:01:00,48866,4.271,False,Distribution
91,James,NaN,2005-01-26,23:00:00,128771,8.309,False,NaN

## The unique and nunique Methods
    * the unique method on a Series returns a collection of its unique values. The method does not exist on a DataFrame.
    * the nunique method returns a count of the number of unique values in the Series/DataFrame.
    * the dropna parameter configures whether to include or exclude missing (NaN) values.

In [42]:
employees["Gender"].unique()

['Male', 'Female', NaN]
Categories (2, str): ['Female', 'Male']

In [43]:
type(employees["Gender"].unique())

pandas.Categorical

In [44]:
employees["Team"].unique()

<StringArray>
[           'Marketing',                    nan,              'Finance',
      'Client Services',                'Legal',              'Product',
          'Engineering', 'Business Development',      'Human Resources',
                'Sales',         'Distribution']
Length: 11, dtype: str

In [45]:
type(employees["Team"].unique())

pandas.arrays.StringArray

In [46]:
employees["Team"].nunique()

10

In [47]:
employees["Team"].nunique(dropna=True)

10

In [48]:
employees["Team"].nunique(dropna=False)

11

In [49]:
employees.nunique()

First Name           200
Gender                 2
Start Date           972
Last Login Time      720
Salary               995
Bonus %              971
Senior Management      2
Team                  10
dtype: int64

In [50]:
employees.nunique(dropna=False)

First Name           201
Gender                 3
Start Date           972
Last Login Time      720
Salary               995
Bonus %              971
Senior Management      2
Team                  11
dtype: int64