# Data Extraction

## Module's Dataset
    * this modul's dataset is a collection of all the James Bond movies.

In [1]:
import pandas as pd

bond = pd.read_csv('data/jamesbond.csv')
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

## The set_index and reset_index Methods
    * the index serves as the collection of primary identifiers/labels/entrypoints for the rows.
    * the fastest way to extract a row is from a sorted index by position/label.
    * Pandas uses index labels/values when merging different objects together.
    * the set_index method sets an existing column as the index of the DataFrame.
    * the reset_index method sets the standard ascending numeric index as the index of the DataFrame.

In [2]:
bond.set_index('Film', inplace=True)
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [3]:
bond.reset_index(inplace=True) # resets the index to the default integer index and moves the 'Film' column back to a regular column

## Retrieve Rows by Index Position with iloc Acessor
    * the iloc accessor retrieves one or more rows by index position.
    * provide a pair of square brackets after the acessor.
    * iloc accepts single values, lists, and slices.

In [4]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [5]:
bond.iloc[5] # returns the 6th row of the dataframe, which is the film "Goldfinger"

Film                 You Only Live Twice
Year                                1967
Actor                       Sean Connery
Director                   Lewis Gilbert
Box Office                         514.2
Budget                              59.9
Bond Actor Salary                    4.4
Name: 5, dtype: object

In [6]:
bond.iloc[3:15] # returns the 4th to 15th rows of the dataframe, which are the films "Dr. No" through "The Man with the Golden Gun"

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [7]:
bond.iloc[:8] # returns the first 8 rows of the dataframe, which are the films "Dr. No" through "Live and Let Die"

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [8]:
bond.iloc[10:] # returns the 11th to the last rows of the dataframe, which are the films "The Spy Who Loved Me" through "Skyfall"

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
26,No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [9]:
bond.iloc[8, 2] # returns the value in the 9th row and 3rd column of the dataframe, which is the budget of the film "The Spy Who Loved Me"

'Roger Moore'

In [10]:
bond.iloc[8:12, 2:4] # returns the values in the 9th to 12th rows and 3rd to 4th columns of the dataframe, which are the budgets and box office revenues of the films "The Spy Who Loved Me" through "Skyfall"

          Actor       Director
8   Roger Moore   Guy Hamilton
9   Roger Moore   Guy Hamilton
10  Roger Moore  Lewis Gilbert
11  Roger Moore  Lewis Gilbert

In [11]:
bond.iloc[3:9, [2, 3, 6]] # returns the values in the 4th to 9th rows and 3rd, 4th, and 7th columns of the dataframe, which are the budgets, box office revenues, and Rotten Tomatoes scores of the films "Dr. No" through "Live and Let Die"

            Actor       Director  Bond Actor Salary
3    Sean Connery  Terence Young                4.7
4     David Niven     Ken Hughes                NaN
5    Sean Connery  Lewis Gilbert                4.4
6  George Lazenby  Peter R. Hunt                0.6
7    Sean Connery   Guy Hamilton                5.8
8     Roger Moore   Guy Hamilton                NaN

In [12]:
bond.iloc[3:9, 3:7] # returns the values in the 4th to 9th rows and 4th to 6th columns of the dataframe, which are the box office revenues, Rotten Tomatoes scores, and Metacritic scores of the films "Dr. No" through "Live and Let Die"

        Director  Box Office  Budget  Bond Actor Salary
3  Terence Young       848.1    41.9                4.7
4     Ken Hughes       315.0    85.0                NaN
5  Lewis Gilbert       514.2    59.9                4.4
6  Peter R. Hunt       291.5    37.3                0.6
7   Guy Hamilton       442.5    34.7                5.8
8   Guy Hamilton       460.3    30.8                NaN

In [13]:
bond.iloc[:10, :3] # returns the values in the first 10 rows and first 3 columns of the dataframe, which are the films "Dr. No" through "The Spy Who Loved Me" and their release years and budgets

                              Film  Year           Actor
0                           Dr. No  1962    Sean Connery
1            From Russia with Love  1963    Sean Connery
2                       Goldfinger  1964    Sean Connery
3                      Thunderball  1965    Sean Connery
4                    Casino Royale  1967     David Niven
5              You Only Live Twice  1967    Sean Connery
6  On Her Majesty's Secret Service  1969  George Lazenby
7             Diamonds Are Forever  1971    Sean Connery
8                 Live and Let Die  1973     Roger Moore
9      The Man with the Golden Gun  1974     Roger Moore

In [14]:
bond.iloc[20:, :3] # returns the values in the 21st to the last rows and first 3 columns of the dataframe, which are the films "Casino Royale" through "Skyfall" and their release years and budgets

                       Film  Year           Actor
20  The World Is Not Enough  1999  Pierce Brosnan
21          Die Another Day  2002  Pierce Brosnan
22            Casino Royale  2006    Daniel Craig
23        Quantum of Solace  2008    Daniel Craig
24                  Skyfall  2012    Daniel Craig
25                  Spectre  2015    Daniel Craig
26           No Time to Die  2021    Daniel Craig

## Retrieve Rows by Index Label with loc Accessor
    * the loc accessor retrieves one or more rows by index label.
    * provide a pair of square brackets after the accessor.
    * Note that it is important to sort the index for labeled index so that loc[] will work properly for retrieving a range of indices.

In [15]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [16]:
bond.set_index('Film', inplace=True)
bond.sort_index(inplace=True) # sorts the dataframe by the index (film titles) in alphabetical order
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [17]:
bond.loc["Goldfinger"] # returns the row of the dataframe corresponding to the film "Goldfinger"

Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object

In [18]:
bond.loc["Casino Royale"] # returns the row of the dataframe corresponding to the film "Casino Royale"

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [19]:
bond.loc[["Goldfinger", "Casino Royale"]] # returns the rows of the dataframe corresponding to the films "Goldfinger" and "Casino Royale"

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [20]:
bond["Diamond Are Forever":"The Spy Who Loved Me"] # returns the rows of the dataframe corresponding to the films "Diamond Are Forever" through "The Spy Who Loved Me"

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN

In [21]:
bond.loc[:"On Her Majesty's Secret Service"] # returns the rows of the dataframe corresponding to the films from the beginning up to and including "On Her Majesty's Secret Service"

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [22]:
bond.loc["Dr. No":] # returns the rows of the dataframe corresponding to the films from "Dr. No" to the end of the dataframe, which are all the films in the dataframe since "Dr. No" is the first film in alphabetical order

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [23]:
bond["Casino Royale":"Skyfall":] 
# returns the rows of the dataframe corresponding to the films "Casino Royale" through "Skyfall", which are all the films in the dataframe 
# since "Casino Royale" is the first film in alphabetical order and "Skyfall" is the last film in alphabetical order

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5

In [24]:
bond[:"Casino Royale"] # returns the rows of the dataframe corresponding to the films from the beginning up to and including "Casino Royale"

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## Second Arguments to loc and iloc accessors
    * the second value inside the square brackets targets the columns.
    * the iloc requires numeric positions for rows and columns.
    * the loc requires labels for rows and columns.

In [25]:
bond.loc["Dr. No", "Actor"] # returns the value in the "Actor" column for the row corresponding to the film "Dr. No"

'Sean Connery'

In [26]:
bond.loc["Casino Royale", ["Actor", "Budget"]] # returns the values in the "Actor" and "Budget" columns for the row corresponding to the film "Casino Royale"

                      Actor  Budget
Film
Casino Royale  Daniel Craig   145.3
Casino Royale   David Niven    85.0

In [27]:
bond.loc["Casino Royale", "Year":"Box Office"] # returns the values in the "Year", "Budget", and "Box Office" columns for the row corresponding to the film "Casino Royale"

               Year         Actor         Director  Box Office
Film
Casino Royale  2006  Daniel Craig  Martin Campbell       581.5
Casino Royale  1967   David Niven       Ken Hughes       315.0

In [28]:
bond.loc["Casino Royale", ["Actor", "Budget", "Year"]] # returns the values in the "Actor", "Budget", and "Year" columns for the row corresponding to the film "Casino Royale"

                      Actor  Budget  Year
Film
Casino Royale  Daniel Craig   145.3  2006
Casino Royale   David Niven    85.0  1967

In [29]:
bond.iloc[3,5] # returns the value in the 4th row and 6th column, which is the film "Thunderball"

np.float64(5.8)

In [30]:
bond.iloc[3, 2] # returns the value in the 4th row and 3rd column, which is the film's box office gross in millions of dollars

'Guy Hamilton'

In [31]:
bond.iloc[4:8, 2:5] # returns the values in the 5th to 8th rows and 3rd to 5th columns of the dataframe, which are the budgets, box office revenues, and Rotten Tomatoes scores of the films "You Only Live Twice" through "Live and Let Die"

                            Director  Box Office  Budget
Film
Die Another Day         Lee Tamahori       465.4   154.2
Dr. No                 Terence Young       448.8     7.0
For Your Eyes Only         John Glen       449.4    60.2
From Russia with Love  Terence Young       543.8    12.6

In [32]:
bond.iloc[3:15, [0, 2]] # returns the values in the 4th to 15th rows and 1st and 3rd columns of the dataframe, which are the release years and budgets of the films "Dr. No" through "The Man

                       Year            Director
Film
Diamonds Are Forever   1971        Guy Hamilton
Die Another Day        2002        Lee Tamahori
Dr. No                 1962       Terence Young
For Your Eyes Only     1981           John Glen
From Russia with Love  1963       Terence Young
GoldenEye              1995     Martin Campbell
Goldfinger             1964        Guy Hamilton
Licence to Kill        1989           John Glen
Live and Let Die       1973        Guy Hamilton
Moonraker              1979       Lewis Gilbert
Never Say Never Again  1983      Irvin Kershner
No Time to Die         2021  Cary Joji Fukunaga

## Overwrite Value in a DataFrame
    * use the iloc or loc accessor on the DataFrame to target a value, then provide the equal sign and a new value.
    * Do not get confuse between bond[] and bond.loc[].
        * bond["Actor"] returns the "Actor" column as a Series.
        * bond.loc["Actor"] returns the row(s) where the index label is "Actor".

In [33]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [34]:
bond["Actor"].loc["Diamonds Are Forever"] = "Sir Sean Connery" 
# updates the value in the "Actor" column for the row corresponding to the film "Diamonds Are Forever" to "Sir Sean Connery"

/tmp/ipykernel_37206/1004379873.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  bond["Actor"].loc["Diamonds Are Forever"] = "Sir Sean Connery"

In [35]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [36]:
bond.loc["Diamonds Are Forever", "Actor"] = "Sir Sean Connery"
# updates the value in the "Actor" column for the row corresponding to the film "Diamonds Are Forever" to "Sir Sean Connery"

In [37]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [38]:
bond["Actor"] # returns the "Actor" column of the dataframe, which contains the names of the actors who played James Bond in each film

Film
A View to a Kill                        Roger Moore
Casino Royale                          Daniel Craig
Casino Royale                           David Niven
Diamonds Are Forever               Sir Sean Connery
Die Another Day                      Pierce Brosnan
Dr. No                                 Sean Connery
For Your Eyes Only                      Roger Moore
From Russia with Love                  Sean Connery
GoldenEye                            Pierce Brosnan
Goldfinger                             Sean Connery
Licence to Kill                      Timothy Dalton
Live and Let Die                        Roger Moore
Moonraker                               Roger Moore
Never Say Never Again                  Sean Connery
No Time to Die                         Daniel Craig
Octopussy                               Roger Moore
On Her Majesty's Secret Service      George Lazenby
Quantum of Solace                      Daniel Craig
Skyfall                                Daniel Craig
Spectre                                Daniel Craig
The Living Daylights                 Timothy Dalton
The Man with the Golden Gun             Roger Moore
The Spy Who Loved Me                    Roger Moore
The World Is Not Enough              Pierce Brosnan
Thunderball                            Sean Connery
Tomorrow Never Dies                  Pierce Brosnan
You Only Live Twice                    Sean Connery
Name: Actor, dtype: str

## Overwrite Multiple Values in a DataFrame
    * the replace method replaces all occurances of a Series value with another value (similar to Find & Replace).
    * to overwrite multiple values in a DataFrame, remember to use an accessor on the DataFrame itself.
    * accessors like loc and iloc can accept Boolean Series. Use them to target the values to overwrite.

In [39]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [40]:
bond["Actor"] = bond["Actor"].replace("Sean Connery", "Sir Sean Connery") # replaces all occurrences of "Sean Connery" with "Sir Sean Connery" in the "Actor" column of the dataframe

In [41]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [42]:
bond[bond["Actor"] == "Sir Sean Connery"].loc[:, "Actor"] = "Sean Connery" 
# this will not work as expected because it creates a copy of the dataframe and modifies the copy instead of the original dataframe. 
# To modify the original dataframe, you can use the .loc indexer to select the rows where the "Actor" column is equal to "Sir Sean Connery" 
# and then assign the value "Sean Connery" to those rows in the "Actor" column.

/tmp/ipykernel_37206/1178980347.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  bond[bond["Actor"] == "Sir Sean Connery"].loc[:, "Actor"] = "Sean Connery"

In [43]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [44]:
# this will work as expected because it uses the .loc indexer to select the rows where the "Actor" column is equal to "Sir Sean Connery" 
# and then assigns the value "Sean Connery" to those rows in the "Actor" column of the original dataframe.
bond.loc[bond["Actor"] == "Sir Sean Connery", "Actor"] = "Sean Connery"
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Rename Index Labels or Columns in a DataFrame
    * the rename method accepts a dictionary for either its columns or index parameters.
    * the dictionary keys represent the existing names and the values represent the new names.
    * we can replace all columns by overwriting the DataFrame's columns attribute.

In [45]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [46]:
bond.rename(columns={"Year": "Year of Release", "Box Office": "Revenue"}, inplace=False) 
# renames the "Year" column to "Year of Release" in the dataframe and the "Box Office" column to "Revenue" in the dataframe, 
# but does not modify the original dataframe because inplace=False is specified. To modify the original dataframe, you can set 
# inplace=True or assign the result of the rename operation back to the original dataframe like this:
# bond = bond.rename(columns={"Year": "Year of Release", "Box Office": "Revenue"})

,Year of Release,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [47]:
swaps = {
    "Dr. No": "Dr. No",
    "Goldeneye": "Goldeneye",
    "The World Is Not Enough": "Best Bond Film Ever",
}
bond.rename(index=swaps, inplace=False) 
# renames the index labels "Dr. No" to "Dr. No", "Goldeneye" to "Goldeneye", and "The World Is Not Enough" to "Best Bond Film Ever" in the dataframe, 
# but does not modify the original dataframe because inplace=False is specified. To modify the original dataframe, you can set inplace=True or assign 
# the result of the rename operation back to the original dataframe like this:          
# bond = bond.rename(index=swaps)

# Note that bond.columns[3] = "Revenue" will not work because the columns attribute of a dataframe is an Index object, which is immutable and does 
# not support item assignment.
# To change the column name, you can use the rename method or assign a new list of column names to the columns attribute of the dataframe like this:
# bond.columns = ["Year", "Actor", "Budget", "Revenue", "Rotten Tomatoes Score", "Metacritic Score", "Salary"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Best Bond Film Ever,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [48]:
bond.columns

Index(['Year', 'Actor', 'Director', 'Box Office', 'Budget',
       'Bond Actor Salary'],
      dtype='str')

In [49]:
new_column_labels = ["Year","Bond Guy","Camera Dude","Revenues","Cost","Salary"]
bond.columns = new_column_labels # assigns the list of new column labels to the columns attribute of the dataframe, which updates the column names in the dataframe to the new labels specified in the list
bond

,Year,Bond Guy,Camera Dude,Revenues,Cost,Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## Delete Rows or Columns from a DataFrame
    * the drop method deletes one or more rows/columns from a DataFrame.
    * pass the index or columns parameters a list of the column names to remove.
    * the pop method and removes and returns a single Series (it mutates the DataFrame in the process).
    * python's del keyword also removes a single Series.

In [50]:
bond = pd.read_csv('data/jamesbond.csv', index_col="Film").sort_index()
bond # reads the CSV file 'jamesbond.csv' into a new dataframe called bond, which will overwrite the existing bond dataframe with the original data from the CSV file

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [51]:
bond.drop(columns=["Year", "Budget"], inplace=False) 
# drops the "Year" and "Budget" columns from the dataframe and modifies the original dataframe because inplace=True is specified.

,Actor,Director,Box Office,Bond Actor Salary
Film,,,,
A View to a Kill,Roger Moore,John Glen,275.2,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,3.3
Casino Royale,David Niven,Ken Hughes,315.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,17.9
Dr. No,Sean Connery,Terence Young,448.8,0.6
For Your Eyes Only,Roger Moore,John Glen,449.4,NaN
From Russia with Love,Sean Connery,Terence Young,543.8,1.6
GoldenEye,Pierce Brosnan,Martin Campbell,518.5,5.1
Goldfinger,Sean Connery,Guy Hamilton,820.4,3.2
Licence to Kill,Timothy Dalton,John Glen,250.9,7.9
Live and Let Die,Roger Moore,Guy Hamilton,460.3,NaN
Moonraker,Roger Moore,Lewis Gilbert,535.0,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,380.0,NaN
No Time to Die,Daniel Craig,Cary Joji Fukunaga,774.2,25.0
Octopussy,Roger Moore,John Glen,373.8,7.8
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,0.6
Quantum of Solace,Daniel Craig,Marc Forster,514.2,8.1
Skyfall,Daniel Craig,Sam Mendes,943.5,14.5
Spectre,Daniel Craig,Sam Mendes,726.7,30.0
The Living Daylights,Timothy Dalton,John Glen,313.5,5.2
The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,NaN
The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,13.5
Thunderball,Sean Connery,Terence Young,848.1,4.7
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,10.0
You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,4.4

In [52]:
bond.drop(index=["Dr. No", "Casino Royale"], inplace=False)
# drops the rows with index labels "Dr. No" and "Casino Royale" from the dataframe and modifies the original dataframe
#  because inplace=True is specified. To modify the original dataframe, you can set inplace=True or assign the result 
# of the drop operation back to the original dataframe like this:
# bond = bond.drop(index=["Dr. No", "Casino Royale"])

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [53]:
bond.drop(index=["Dr. No", "Casino Royale"], columns=["Year", "Budget"], inplace=False)

,Actor,Director,Box Office,Bond Actor Salary
Film,,,,
A View to a Kill,Roger Moore,John Glen,275.2,9.1
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,17.9
For Your Eyes Only,Roger Moore,John Glen,449.4,NaN
From Russia with Love,Sean Connery,Terence Young,543.8,1.6
GoldenEye,Pierce Brosnan,Martin Campbell,518.5,5.1
Goldfinger,Sean Connery,Guy Hamilton,820.4,3.2
Licence to Kill,Timothy Dalton,John Glen,250.9,7.9
Live and Let Die,Roger Moore,Guy Hamilton,460.3,NaN
Moonraker,Roger Moore,Lewis Gilbert,535.0,NaN
Never Say Never Again,Sean Connery,Irvin Kershner,380.0,NaN
No Time to Die,Daniel Craig,Cary Joji Fukunaga,774.2,25.0
Octopussy,Roger Moore,John Glen,373.8,7.8
On Her Majesty's Secret Service,George Lazenby,Peter R. Hunt,291.5,0.6
Quantum of Solace,Daniel Craig,Marc Forster,514.2,8.1
Skyfall,Daniel Craig,Sam Mendes,943.5,14.5
Spectre,Daniel Craig,Sam Mendes,726.7,30.0
The Living Daylights,Timothy Dalton,John Glen,313.5,5.2
The Man with the Golden Gun,Roger Moore,Guy Hamilton,334.0,NaN
The Spy Who Loved Me,Roger Moore,Lewis Gilbert,533.0,NaN
The World Is Not Enough,Pierce Brosnan,Michael Apted,439.5,13.5
Thunderball,Sean Connery,Terence Young,848.1,4.7
Tomorrow Never Dies,Pierce Brosnan,Roger Spottiswoode,463.2,10.0
You Only Live Twice,Sean Connery,Lewis Gilbert,514.2,4.4

In [54]:
bond.pop("Year") 
# removes the "Year" column from the dataframe and returns it as a Series. 
# The original dataframe is modified and the "Year" column is no longer present in the dataframe.

Film
A View to a Kill                   1985
Casino Royale                      2006
Casino Royale                      1967
Diamonds Are Forever               1971
Die Another Day                    2002
Dr. No                             1962
For Your Eyes Only                 1981
From Russia with Love              1963
GoldenEye                          1995
Goldfinger                         1964
Licence to Kill                    1989
Live and Let Die                   1973
Moonraker                          1979
Never Say Never Again              1983
No Time to Die                     2021
Octopussy                          1983
On Her Majesty's Secret Service    1969
Quantum of Solace                  2008
Skyfall                            2012
Spectre                            2015
The Living Daylights               1987
The Man with the Golden Gun        1974
The Spy Who Loved Me               1977
The World Is Not Enough            1999
Thunderball                        1965
Tomorrow Never Dies                1997
You Only Live Twice                1967
Name: Year, dtype: int64

In [55]:
bond.head()

,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,
A View to a Kill,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [56]:
del bond["Budget"] # removes the "Budget" column from the dataframe and modifies the original dataframe.

In [57]:
bond.head()

,Actor,Director,Box Office,Bond Actor Salary
Film,,,,
A View to a Kill,Roger Moore,John Glen,275.2,9.1
Casino Royale,Daniel Craig,Martin Campbell,581.5,3.3
Casino Royale,David Niven,Ken Hughes,315.0,NaN
Diamonds Are Forever,Sean Connery,Guy Hamilton,442.5,5.8
Die Another Day,Pierce Brosnan,Lee Tamahori,465.4,17.9

## Create Random Sample with the sample Method
    * the sample method returns a specified one or more random rows from the DataFrame.
    * customize the axis parameter to extract random columns.

In [58]:
bond = pd.read_csv('data/jamesbond.csv', index_col="Film").sort_index()
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [59]:
bond.sample(n=5) 
# returns a random sample of 5 rows from the dataframe, which can be useful for quickly inspecting a subset of the 
# data or for testing purposes. The original dataframe is not modified by this operation.

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7

In [60]:
bond.sample(n=2, axis="rows") 
# returns a random sample of 2 rows from the dataframe, which can be useful for quickly inspecting a subset of the 
# data or for testing purposes. The original dataframe is not modified by this operation.

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5

In [61]:
bond.sample(n=2, axis="columns") 
# returns a random sample of 2 columns from the dataframe, which can be useful for quickly inspecting a subset of the 
# data or for testing purposes. The original dataframe is not modified by this operation.

                                           Director  Box Office
Film
A View to a Kill                          John Glen       275.2
Casino Royale                       Martin Campbell       581.5
Casino Royale                            Ken Hughes       315.0
Diamonds Are Forever                   Guy Hamilton       442.5
Die Another Day                        Lee Tamahori       465.4
Dr. No                                Terence Young       448.8
For Your Eyes Only                        John Glen       449.4
From Russia with Love                 Terence Young       543.8
GoldenEye                           Martin Campbell       518.5
Goldfinger                             Guy Hamilton       820.4
Licence to Kill                           John Glen       250.9
Live and Let Die                       Guy Hamilton       460.3
Moonraker                             Lewis Gilbert       535.0
Never Say Never Again                Irvin Kershner       380.0
No Time to Die                   Cary Joji Fukunaga       774.2
Octopussy                                 John Glen       373.8
On Her Majesty's Secret Service       Peter R. Hunt       291.5
Quantum of Solace                      Marc Forster       514.2
Skyfall                                  Sam Mendes       943.5
Spectre                                  Sam Mendes       726.7
The Living Daylights                      John Glen       313.5
The Man with the Golden Gun            Guy Hamilton       334.0
The Spy Who Loved Me                  Lewis Gilbert       533.0
The World Is Not Enough               Michael Apted       439.5
Thunderball                           Terence Young       848.1
Tomorrow Never Dies              Roger Spottiswoode       463.2
You Only Live Twice                   Lewis Gilbert       514.2

## The nsmallest and nlargest Methods
    * the nlargest method returns a specified number of rows with the largest values from a given column.
    * the nsmallest method returns rows with the smallest values from a given column.
    * the nlargest and nsmallest methods are more efficient than sorting the entire DataFrame.
    * only works on numeric values.

In [62]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,30.0
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [63]:
bond.nlargest(n=4, columns="Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
No Time to Die,2021,Daniel Craig,Cary Joji Fukunaga,774.2,301.0,25.0

In [64]:
bond["Box Office"].nlargest(n=4)
# returns the "Box Office" column of the dataframe (a Series), which contains the box office revenues of each film in millions of dollars

Film
Skyfall           943.5
Thunderball       848.1
Goldfinger        820.4
No Time to Die    774.2
Name: Box Office, dtype: float64

In [65]:
bond.nsmallest(n=3, columns=["Box Office", "Budget", "Bond Actor Salary"])
# returns the 3 rows of the dataframe with the smallest values in the "Box Office", "Budget", and "Bond Actor Salary" columns, 
# which are the films with the lowest box office revenues, budgets, and actor salaries. The original dataframe is not modified by this operation.

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

## Filtering with the where Method
    * similar to square brackets or loc, the where method filters the original DataFrame with a Boolean Series.
    * Pandas will populate rows that do not match the criteria with NaN values.
    * leaving in the NaN values can be advantageous for certain merge and visualization operations.

In [66]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [67]:
is_sean_connery = bond["Actor"] == "Sean Connery"
bond.where(cond=is_sean_connery)
# returns a new dataframe where the rows that satisfy the condition (where the "Actor" column is equal to "Sean Connery") 
# are kept unchanged, and the rows that do not satisfy the condition are replaced with NaN (Not a Number) values. The original 
# dataframe is not modified by this operation.

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
No Time to Die,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

## The apply Method with DataFrames
    * the apply method invokes a function on every column or every row in the DataFrame.
    * pass the uninvoked function as the first argument to the apply method.
    * pass the axis parameter an argument of "columns" to invoke the function on every row.
    * pandas will pass in the row's values as a Series object. We can use accessors like loc and iloc to extract the column's values for that row.

In [68]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [69]:
bond["Actor"].apply(len)
# applies the len function to each value in the "Actor" column of the dataframe, which returns a new Series where each 
# value is the length of the corresponding actor's name in the "Actor" column. The original dataframe is not modified by this operation.

Film
A View to a Kill                   11
Casino Royale                      12
Casino Royale                      11
Diamonds Are Forever               12
Die Another Day                    14
Dr. No                             12
For Your Eyes Only                 11
From Russia with Love              12
GoldenEye                          14
Goldfinger                         12
Licence to Kill                    14
Live and Let Die                   11
Moonraker                          11
Never Say Never Again              12
No Time to Die                     12
Octopussy                          11
On Her Majesty's Secret Service    14
Quantum of Solace                  12
Skyfall                            12
Spectre                            12
The Living Daylights               14
The Man with the Golden Gun        11
The Spy Who Loved Me               11
The World Is Not Enough            14
Thunderball                        12
Tomorrow Never Dies                14
You Only Live Twice                12
Name: Actor, dtype: int64

In [70]:
def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc["Actor"]
    budget = row.loc["Budget"]

    if year >= 1980 and year < 1990 :
        return "Great 80's flick!"
    
    if actor == "Pierce Brosnan":
        return "The best Bond ever!"
    
    if budget > 100:
        return "Expensive movie, fun!"
    
    return "No comment."
    
bond.apply(rank_movie, axis="columns")
# applies the rank_movie function to each row of the dataframe (axis=1), which returns a new Series where each value is the result of 
# applying the rank_movie function to the corresponding row of the dataframe. The original dataframe is not modified by this operation.

Film
A View to a Kill                       Great 80's flick!
Casino Royale                      Expensive movie, fun!
Casino Royale                                No comment.
Diamonds Are Forever                         No comment.
Die Another Day                      The best Bond ever!
Dr. No                                       No comment.
For Your Eyes Only                     Great 80's flick!
From Russia with Love                        No comment.
GoldenEye                            The best Bond ever!
Goldfinger                                   No comment.
Licence to Kill                        Great 80's flick!
Live and Let Die                             No comment.
Moonraker                                    No comment.
Never Say Never Again                  Great 80's flick!
No Time to Die                     Expensive movie, fun!
Octopussy                              Great 80's flick!
On Her Majesty's Secret Service              No comment.
Quantum of Solace                  Expensive movie, fun!
Skyfall                            Expensive movie, fun!
Spectre                            Expensive movie, fun!
The Living Daylights                   Great 80's flick!
The Man with the Golden Gun                  No comment.
The Spy Who Loved Me                         No comment.
The World Is Not Enough              The best Bond ever!
Thunderball                                  No comment.
Tomorrow Never Dies                  The best Bond ever!
You Only Live Twice                          No comment.
dtype: str