## Working with Text

In [52]:
import pandas as pd

chicago = pd.read_csv('data/chicago.csv').dropna(how='all')
chicago

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...,...
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [53]:
chicago.info()

<class 'pandas.DataFrame'>
RangeIndex: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  str
 1   Position Title          32062 non-null  str
 2   Department              32062 non-null  str
 3   Employee Annual Salary  32062 non-null  str
dtypes: str(4)
memory usage: 1002.1 KB

In [54]:
chicago.nunique()

Name                      31776
Position Title             1093
Department                   35
Employee Annual Salary     1156
dtype: int64

In [55]:
chicago["Department"] = chicago["Department"].astype("category")

In [56]:
chicago

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...,...
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

## Common String Methods
    * a Series has a special str attribute that expose an object with string methods.
    * Access the str attribute, then invoke the string method on the nested object.
    * Most method names will match their Python method equivalents (e.g. upper, lower, title, etc)

In [57]:
chicago["Position Title"].str.lower()
# must use .str to apply string methods to a Series of strings

0                      water rate taker
1                        police officer
2                        police officer
3              chief contract expediter
4                     civil engineer iv
                      ...
32057    frm of machinists - automotive
32058                    police officer
32059                    police officer
32060                    police officer
32061           chief data base analyst
Name: Position Title, Length: 32062, dtype: str

In [58]:
chicago["Department"].str.replace("MGMNT", "MANAGEMENT").str.title()
# can chain string methods together to perform multiple operations at once

0        Water Management
1                  Police
2                  Police
3        General Services
4        Water Management
               ...
32057    General Services
32058              Police
32059              Police
32060              Police
32061                Doit
Name: Department, Length: 32062, dtype: str

## Filtering with String Methods
    * the str.contains method checks whether a substring exists anywhere in the string
    * the str.startwith method checks whether a substring exists at the start of the string.
    * the str.endwith method checks whether a substring exists at the end of the string.

In [59]:
water_workers = chicago["Position Title"].str.lower().str.contains("water")
chicago[water_workers].head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [60]:
starts_with_civil = chicago["Position Title"].str.lower().str.startswith("civil")
chicago[starts_with_civil].head()

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
25,"ABDULSATTAR, MUDHAR",CIVIL ENGINEER II,WATER MGMNT,$58536.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
55,"ABUTALEB, AHMAD H",CIVIL ENGINEER II,WATER MGMNT,$89676.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00

In [61]:
ends_with_iv = chicago["Position Title"].str.lower().str.endswith("iv")
chicago[ends_with_iv].head()

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
145,"ADAMS, SHERYLL A",LIBRARIAN IV,PUBLIC LIBRARY,$97812.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
166,"ADENI, MOHAMED K",ACCOUNTANT IV,FINANCE,$97812.00

## String Methods on Index and Columns
    * use the index and columns attributes to access the DataFrame index/column labels.
    * these objects support string methods via their own str attribute.

In [62]:
chicago = pd.read_csv('data/chicago.csv', index_col="Name").dropna(how='all').sort_index()
chicago["Department"] = chicago["Department"].astype("category")
chicago

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...
"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [63]:
chicago.index

Index(['AARON,  ELVIA J', 'AARON,  JEFFERY M', 'AARON,  KARINA',
       'AARON,  KIMBERLEI R', 'ABAD JR,  VICENTE M', 'ABARCA,  ANABEL',
       'ABARCA,  EMMANUEL', 'ABASCAL,  REECE E', 'ABBASI,  CHRISTOPHER',
       'ABBATACOLA,  ROBERT J',
       ...
       'ZWIT,  JEFFREY J', 'ZWOLFER,  MATTHEW W', 'ZYCH,  MATEUSZ',
       'ZYDEK,  BRYAN', 'ZYGADLO,  JOHN P', 'ZYGADLO,  MICHAEL J',
       'ZYGOWICZ,  PETER J', 'ZYMANTAS,  MARK E', 'ZYRKOWSKI,  CARLO E',
       'ZYSKOWSKI,  DARIUSZ'],
      dtype='str', name='Name', length=32062)

In [64]:
chicago.index = chicago.index.str.strip().str.title()
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [65]:
chicago.columns = chicago.columns.str.upper()
chicago

,POSITION TITLE,DEPARTMENT,EMPLOYEE ANNUAL SALARY
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...
"Zygadlo, Michael J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
"Zygowicz, Peter J",POLICE OFFICER,POLICE,$87384.00
"Zymantas, Mark E",POLICE OFFICER,POLICE,$84450.00
"Zyrkowski, Carlo E",POLICE OFFICER,POLICE,$87384.00
"Zyskowski, Dariusz",CHIEF DATA BASE ANALYST,DoIT,$113664.00

## The split Method
    * the str.split method splits a string by the occurrence of a delimiter. Pandas returns a Series of lists.
    * use the str.get method to access a nested list element by its index position.

In [66]:
chicago = pd.read_csv('data/chicago.csv', index_col="Name").dropna(how='all').sort_index()
chicago["Department"] = chicago["Department"].astype("category")
chicago

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
...,...,...,...
"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00
"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00
"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00
"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00
"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00

In [67]:
# The most common first word in "Position Title"

chicago["Position Title"].str.split(" ").str.get(0).value_counts()
# can split strings into lists and then use .str.get() to access specific elements of the list

Position Title
POLICE             10856
FIREFIGHTER-EMT     1509
SERGEANT            1186
POOL                 918
FIREFIGHTER          810
                   ...
COMM                   1
EQUAL                  1
HATE                   1
DECK                   1
PREPRESS               1
Name: count, Length: 320, dtype: int64

In [68]:
# Finding the most common first name among the employees in the dataset
chicago.index.str.title().str.split(", ").str.get(1).str.strip().str.split(" ").str.get(0).value_counts()

Name
Michael    1153
John        899
James       676
Robert      622
Joseph      537
           ...
Hamzeh        1
Janaan        1
Alen          1
Jurdon        1
Mac           1
Name: count, Length: 5091, dtype: int64

## The expand and n Parameters of the split Method
    * the expand parameter returns a DataFrame instead of a Series of lists.
    * the n parameter limits the number of splits.

In [69]:
chicago.reset_index(drop=False, inplace=True)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [ ]:
# we specify a 2 columns list on the left hand side because the right hand side produces a DataFrame with 2 columns (the result of str.split with expand=True)
chicago[["Last Name", "First Name"]] = chicago["Name"].str.split(",", expand=True)
chicago

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,AARON,ELVIA J
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,AARON,JEFFERY M
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,AARON,KARINA
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,AARON,KIMBERLEI R
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,ABAD JR,VICENTE M
...,...,...,...,...,...,...
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00,ZYGADLO,MICHAEL J
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00,ZYGOWICZ,PETER J
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00,ZYMANTAS,MARK E
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00,ZYRKOWSKI,CARLO E
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00,ZYSKOWSKI,DARIUSZ

In [72]:
# Splitting and expanding for n number of times
chicago[["Primary Title", "Secondary Title"]] = chicago["Position Title"].str.split(" ", expand=True, n=1)
chicago

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name,Primary Title,Secondary Title
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,AARON,ELVIA J,WATER,RATE TAKER
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,AARON,JEFFERY M,POLICE,OFFICER
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,AARON,KARINA,POLICE,OFFICER
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,AARON,KIMBERLEI R,CHIEF,CONTRACT EXPEDITER
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,ABAD JR,VICENTE M,CIVIL,ENGINEER IV
...,...,...,...,...,...,...,...,...
32057,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,$99528.00,ZYGADLO,MICHAEL J,FRM,OF MACHINISTS - AUTOMOTIVE
32058,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,$87384.00,ZYGOWICZ,PETER J,POLICE,OFFICER
32059,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,$84450.00,ZYMANTAS,MARK E,POLICE,OFFICER
32060,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,$87384.00,ZYRKOWSKI,CARLO E,POLICE,OFFICER
32061,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,$113664.00,ZYSKOWSKI,DARIUSZ,CHIEF,DATA BASE ANALYST