## Merging DataFrames

In [1]:
import pandas as pd

foods = pd.read_csv("data/restaurant_foods.csv", index_col="Food ID")
customers = pd.read_csv("data/restaurant_customers.csv", index_col="ID")

week1 = pd.read_csv("data/restaurant_week_1_sales.csv")
week2 = pd.read_csv("data/restaurant_week_2_sales.csv")

In [2]:
foods

          Food Item  Price
Food ID
1             Sushi   3.99
2           Burrito   9.99
3              Taco   2.99
4        Quesadilla   4.25
5             Pizza   2.49
6             Pasta  13.99
7             Steak  24.99
8             Salad  11.25
9             Donut   0.99
10            Drink   1.75

In [3]:
customers

     First Name Last Name  Gender       Company                     Occupation
ID
1        Joseph   Perkins    Male       Dynazzy  Community Outreach Specialist
2      Jennifer   Alvarez  Female          DabZ        Senior Quality Engineer
3         Roger     Black    Male       Tagfeed              Account Executive
4        Steven     Evans    Male          Fatz               Registered Nurse
5          Judy  Morrison  Female       Demivee                Legal Assistant
...         ...       ...     ...           ...                            ...
996       Debra    Garcia  Female  Dazzlesphere            Structural Engineer
997     Douglas    Bishop    Male      Livepath                    Developer I
998       Frank  Franklin    Male    Brainverse             Nurse Practicioner
999     Jessica     Burns  Female    Babbleblab              Financial Advisor
1000      Brian   Daniels    Male         Tazzy     Physical Therapy Assistant

[1000 rows x 5 columns]

In [4]:
week1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [5]:
week2

     Customer ID  Food ID
0            688       10
1            813        7
2            495       10
3            189        5
4            267        3
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[250 rows x 2 columns]

## The pd.concat Function
    * the concat function concatenates one DataFrame to the end of another.
    * the original index labels will be kept by default. Set ignore_index to True to generate a new index.
    * the keys parameter create a MultiIndex using the specified keys/labels.
    * pandas will concatenate the DataFrames along the row/index axis.
    * pandas will include all columns that exist in either DataFrame. If there are no matching values, pandas will use NaN values.
    * we can pass the axis parameter an argument of "columns" to concatenate on the column axis.

In [6]:
pd.concat([week1, week2])

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[500 rows x 2 columns]

In [7]:
pd.concat([week1, week2], ignore_index=True)

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
495          783       10
496          556       10
497          547        9
498          252        9
499          249        6

[500 rows x 2 columns]

In [8]:
pd.concat([week1, week2], keys=["Week 1","Week 2"]) # returns a multi index dataframe

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [9]:
df1 = pd.DataFrame([1,2,3], columns=["A"])
df2 = pd.DataFrame([1,2,3], columns=["B"])

pd.concat([df1,df2])
# since the column labels in the two df are different, pandas will simply append the df2 to df1 with two different columns.
# this default behaviour is merging along the index axis.

     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  1.0
1  NaN  2.0
2  NaN  3.0

In [10]:
pd.concat([df1,df2],axis="index") # same as the above, default behaviour is merge along the index axis, i.e. vertically

     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  1.0
1  NaN  2.0
2  NaN  3.0

In [11]:
pd.concat([df1,df2], axis="columns") # merge along the column axis, i.e. horizontally

   A  B
0  1  1
1  2  2
2  3  3

In [12]:
df3 = df2.rename({"B":"A"}, axis=1)
df3

   A
0  1
1  2
2  3

In [13]:
pd.concat([df1,df3]) # default merging behaviour where the two dataframes have the same column labels.

   A
0  1
1  2
2  3
0  1
1  2
2  3

In [14]:
pd.concat([df1,df3], axis="index") # same as above

   A
0  1
1  2
2  3
0  1
1  2
2  3

In [15]:
pd.concat([df1,df3], axis="columns") # merge horizontally

   A  A
0  1  1
1  2  2
2  3  3

In [16]:
pd.concat([df1,df3], ignore_index=True) # merge vertically and reindex

   A
0  1
1  2
2  3
3  1
4  2
5  3

## Left Joins
    * the merge method joins two DataFrames together based on shared values in a column or an index.
    * a left join merges one DataFrame into another based on values in the first one.
    * the left DataFrame is the one we invoke the merge method on.
    * if the left DataFrame's value is not found in the right DataFrame, the row will hold NaN values.

In [17]:
week1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [18]:
foods

          Food Item  Price
Food ID
1             Sushi   3.99
2           Burrito   9.99
3              Taco   2.99
4        Quesadilla   4.25
5             Pizza   2.49
6             Pasta  13.99
7             Steak  24.99
8             Salad  11.25
9             Donut   0.99
10            Drink   1.75

In [19]:
# for each customer transaction in week1, which food item did the customer ordered
week1.merge(right=foods, how="left", on="Food ID")

     Customer ID  Food ID   Food Item  Price
0            537        9       Donut   0.99
1             97        4  Quesadilla   4.25
2            658        1       Sushi   3.99
3            202        2     Burrito   9.99
4            155        9       Donut   0.99
..           ...      ...         ...    ...
245          413        9       Donut   0.99
246          926        6       Pasta  13.99
247          134        3        Taco   2.99
248          396        6       Pasta  13.99
249          535       10       Drink   1.75

[250 rows x 4 columns]

In [20]:
# for each food item, which customer order it in week1
foods.merge(right=week1, how="left", on="Food ID")

     Food ID Food Item  Price  Customer ID
0          1     Sushi   3.99          658
1          1     Sushi   3.99          600
2          1     Sushi   3.99          155
3          1     Sushi   3.99          341
4          1     Sushi   3.99           20
..       ...       ...    ...          ...
245       10     Drink   1.75          809
246       10     Drink   1.75          584
247       10     Drink   1.75          274
248       10     Drink   1.75          151
249       10     Drink   1.75          535

[250 rows x 4 columns]

In [21]:
# Food Item order count in week1
foods.merge(right=week1, how="left", on="Food ID").value_counts("Food Item")

Food Item
Donut         35
Pasta         28
Steak         27
Burrito       26
Sushi         24
Drink         24
Taco          23
Salad         23
Quesadilla    21
Pizza         19
Name: count, dtype: int64

## The left_on and right_on Parameters
    * the left_on and right_on parameters designate the column names from each DataFrame to use in the merge.
    * this means we need not rename the join column names.

In [22]:
week2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [23]:
customers.head()

   First Name Last Name  Gender  Company                     Occupation
ID
1      Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
2    Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
3       Roger     Black    Male  Tagfeed              Account Executive
4      Steven     Evans    Male     Fatz               Registered Nurse
5        Judy  Morrison  Female  Demivee                Legal Assistant

In [24]:
week2.merge(customers, how="left", left_on="Customer ID", right_on="ID")
# note the right join column ("ID") is not shown in the result as it is the index of the right table.

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,688,10,Carl,Williamson,Male,Thoughtmix,Graphic Designer
1,813,7,Johnny,Walker,Male,Kayveo,Developer II
2,495,10,Deborah,Little,Female,Babbleblab,VP Accounting
3,189,5,Roger,Gordon,Male,Skilith,Operator
4,267,3,Matthew,Wood,Male,Agimba,Product Engineer
...,...,...,...,...,...,...,...
245,783,10,Phyllis,Meyer,Female,Voolia,Information Systems Manager
246,556,10,Samuel,Bailey,Male,Oyoloo,Nurse
247,547,9,Tina,Watkins,Female,Thoughtstorm,Accountant II
248,252,9,Douglas,Powell,Male,Jetwire,Geologist IV
249,249,6,Anthony,Carpenter,Male,Shuffletag,Health Coach I

## Inner Joins
    * inner joins merge two tables based on shared/common values in columns.
    * if only one DataFrame has a value, pandas will exclude it from the final results set.
    * if the same ID occurs multiple times, pandas will store each possible combination of the values.
    * the design of the join ensures that the results will be the same no matter wheat DataFrame the merge method is invoked upon.
    * we can pass multiple arguments to the on parameter of the merge method. Pandas will require matches in both columns across the DataFrames.

In [25]:
week1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [26]:
week2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [27]:
# the customers that came in in both weeks
week1.merge(week2, how="inner", on="Customer ID")

    Customer ID  Food ID_x  Food ID_y
0           537          9          5
1           155          9          3
2           503          5          8
3           503          5          9
4           155          1          3
..          ...        ...        ...
57          945          5          4
58          343          3          5
59          343          3          2
60          343          3          7
61          621          9          6

[62 rows x 3 columns]

In [28]:
t = week1.merge(week2, how="inner", on="Customer ID", suffixes=[" - Week 1", " - Week 2"])
t

    Customer ID  Food ID - Week 1  Food ID - Week 2
0           537                 9                 5
1           155                 9                 3
2           503                 5                 8
3           503                 5                 9
4           155                 1                 3
..          ...               ...               ...
57          945                 5                 4
58          343                 3                 5
59          343                 3                 2
60          343                 3                 7
61          621                 9                 6

[62 rows x 3 columns]

In [29]:
# multiple rows with same Customer ID in week 1
week1[week1["Customer ID"] == 77]

     Customer ID  Food ID
35            77        1
129           77        9
144           77        2
227           77        9

In [30]:
week2[week2["Customer ID"] == 77]

     Customer ID  Food ID
162           77        7

In [31]:
# all possible join result for the same Customer ID

t[t["Customer ID"] == 77]

    Customer ID  Food ID - Week 1  Food ID - Week 2
8            77                 1                 7
36           77                 9                 7
39           77                 2                 7
55           77                 9                 7

In [32]:
# the "on" parameter

week1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [33]:
week2

     Customer ID  Food ID
0            688       10
1            813        7
2            495       10
3            189        5
4            267        3
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[250 rows x 2 columns]

In [34]:
# customers that came in on both weeks and order the same food
week1.merge(week2, how="inner", on=["Customer ID", "Food ID"], suffixes=[" - Week 1", " - Week 2"]) 
# suffixes is not needed since both table has same column names.

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5          922        1
6           21        4
7          578        5
8          578        5

In [35]:
week1[(week1["Customer ID"] == 21) & (week1["Food ID"] == 4)]

     Customer ID  Food ID
101           21        4
212           21        4

In [36]:
week2[(week2["Customer ID"] == 21) & (week2["Food ID"] == 4)]

    Customer ID  Food ID
30           21        4

## Full-Outer Joins
    * a full/outer joins values that are found in either DataFrame or both DataFrames.
    * pandas does not mind if a value exists in one DataFrame but not the other.
    * if a value does not exist in one DataFrame, it will have a NaN.

In [37]:
week1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [38]:
week2

     Customer ID  Food ID
0            688       10
1            813        7
2            495       10
3            189        5
4            267        3
..           ...      ...
245          783       10
246          556       10
247          547        9
248          252        9
249          249        6

[250 rows x 2 columns]

In [39]:
week1.merge(week2, how="outer", on="Customer ID", suffixes=[" - Week 1", " - Week 2"])

     Customer ID  Food ID - Week 1  Food ID - Week 2
0              3               2.0               NaN
1              8               NaN               6.0
2             10               2.0               NaN
3             13               NaN               2.0
4             20               1.0               NaN
..           ...               ...               ...
449          985               5.0               NaN
450          991               2.0               NaN
451          994               NaN               2.0
452          996               NaN              10.0
453         1000               2.0               NaN

[454 rows x 3 columns]

In [40]:
# same as above with indicator flag
week1.merge(week2, how="outer", on="Customer ID", suffixes=[" - Week 1", " - Week 2"], indicator=True)

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
0              3               2.0               NaN   left_only
1              8               NaN               6.0  right_only
2             10               2.0               NaN   left_only
3             13               NaN               2.0  right_only
4             20               1.0               NaN   left_only
..           ...               ...               ...         ...
449          985               5.0               NaN   left_only
450          991               2.0               NaN   left_only
451          994               NaN               2.0  right_only
452          996               NaN              10.0  right_only
453         1000               2.0               NaN   left_only

[454 rows x 4 columns]

In [41]:
# same as above with custom label
t = week1.merge(week2, how="outer", on="Customer ID", suffixes=[" - Week 1", " - Week 2"], indicator="Merge Indicator")
t.head(20)

    Customer ID  Food ID - Week 1  Food ID - Week 2 Merge Indicator
0             3               2.0               NaN       left_only
1             8               NaN               6.0      right_only
2            10               2.0               NaN       left_only
3            13               NaN               2.0      right_only
4            20               1.0               NaN       left_only
5            21               4.0               4.0            both
6            21               4.0               4.0            both
7            24               NaN               8.0      right_only
8            26               9.0               NaN       left_only
9            27               NaN               4.0      right_only
10           30               2.0               4.0            both
11           35               NaN               8.0      right_only
12           38               4.0               NaN       left_only
13           39               NaN              10.0      right_only
14           45               7.0               8.0            both
15           46               NaN               6.0      right_only
16           47               8.0               NaN       left_only
17           51               2.0               NaN       left_only
18           51              10.0               NaN       left_only
19           53               2.0               NaN       left_only

In [42]:
t["Merge Indicator"].value_counts()

Merge Indicator
right_only    197
left_only     195
both           62
Name: count, dtype: int64

In [43]:
t[t["Merge Indicator"].isin(["left_only","right_only"])].head(20)

    Customer ID  Food ID - Week 1  Food ID - Week 2 Merge Indicator
0             3               2.0               NaN       left_only
1             8               NaN               6.0      right_only
2            10               2.0               NaN       left_only
3            13               NaN               2.0      right_only
4            20               1.0               NaN       left_only
7            24               NaN               8.0      right_only
8            26               9.0               NaN       left_only
9            27               NaN               4.0      right_only
11           35               NaN               8.0      right_only
12           38               4.0               NaN       left_only
13           39               NaN              10.0      right_only
15           46               NaN               6.0      right_only
16           47               8.0               NaN       left_only
17           51               2.0               NaN       left_only
18           51              10.0               NaN       left_only
19           53               2.0               NaN       left_only
20           54               NaN               8.0      right_only
21           55               NaN               9.0      right_only
22           55               NaN               4.0      right_only
23           56               NaN               3.0      right_only

## Merging by Indexes with the left_index and right_index Parameters
    * use the on parameter if the column(s) to be matched on have the same names in both DataFrames.
    * use the left_on and right_on parameters if the column(s) to be matched on have different names in the two DataFrames.
    * use the left_index or right_index parameters (set to True) if the values to be matched on are found in the index of a DataFrame.

In [44]:
week1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [45]:
customers

     First Name Last Name  Gender       Company                     Occupation
ID
1        Joseph   Perkins    Male       Dynazzy  Community Outreach Specialist
2      Jennifer   Alvarez  Female          DabZ        Senior Quality Engineer
3         Roger     Black    Male       Tagfeed              Account Executive
4        Steven     Evans    Male          Fatz               Registered Nurse
5          Judy  Morrison  Female       Demivee                Legal Assistant
...         ...       ...     ...           ...                            ...
996       Debra    Garcia  Female  Dazzlesphere            Structural Engineer
997     Douglas    Bishop    Male      Livepath                    Developer I
998       Frank  Franklin    Male    Brainverse             Nurse Practicioner
999     Jessica     Burns  Female    Babbleblab              Financial Advisor
1000      Brian   Daniels    Male         Tazzy     Physical Therapy Assistant

[1000 rows x 5 columns]

In [46]:
week1.merge(customers, how="left", left_on="Customer ID", right_index=True).merge(foods, how="left", left_on="Food ID", right_index=True)

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation,Food Item,Price
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse,Donut,0.99
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator,Quesadilla,4.25
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist,Sushi,3.99
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III,Burrito,9.99
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III,Donut,0.99
...,...,...,...,...,...,...,...,...,...
245,413,9,Diane,Bailey,Female,Wikibox,Technical Writer,Donut,0.99
246,926,6,Anne,Wagner,Female,Skyba,Legal Assistant,Pasta,13.99
247,134,3,Diana,Hall,Female,Quinu,Financial Advisor,Taco,2.99
248,396,6,Juan,Romero,Male,Zoonder,Analyst Programmer,Pasta,13.99
249,535,10,Nancy,Cox,Female,Trudeo,Research Associate,Drink,1.75

## The join Method
    * the join method is a shortcut for caoncatenating two DataFrames when merging by index labels.

In [47]:
week1_times = pd.read_csv("data/restaurant_week_1_times.csv")
week1_times

    Time of Day
0      14:54:59
1      20:55:17
2      01:16:22
3      16:17:26
4      19:26:11
..          ...
245    04:44:14
246    07:46:21
247    20:45:08
248    01:09:06
249    18:18:50

[250 rows x 1 columns]

In [48]:
week1

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
..           ...      ...
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10

[250 rows x 2 columns]

In [49]:
# instead of using merge(), we can also use the join() method to merge the week1_times to week1
week1.join(week1_times)

     Customer ID  Food ID Time of Day
0            537        9    14:54:59
1             97        4    20:55:17
2            658        1    01:16:22
3            202        2    16:17:26
4            155        9    19:26:11
..           ...      ...         ...
245          413        9    04:44:14
246          926        6    07:46:21
247          134        3    20:45:08
248          396        6    01:09:06
249          535       10    18:18:50

[250 rows x 3 columns]