## Working with Dates and Times

In [1]:
import pandas as pd
import datetime as dt

### Review of Python's datetime Module
    * the datetime module is built into the core Python programming language.
    * the common alias for the datetime module is dt.
    * a module is a Python source file, think of it like an internal library that Python loads on demand.
    * the datetime module includes date and datetime classes for representing dates and datetimes.
    * the date constructor accepts arguments for year, month and day. Python defaults to 0 for any missing value.
    * the datetime constructor accepts arguments for year, month, day, hour, minute, and second.

In [2]:
someday = dt.date(2025, 12, 15)
someday

datetime.date(2025, 12, 15)

In [3]:
someday.year

2025

In [4]:
somedate = dt.datetime(2025,5,12, 16, 22, 34)
somedate

datetime.datetime(2025, 5, 12, 16, 22, 34)

In [5]:
somedate.month

5

In [6]:
somedate.hour

16

### The Timestamp and DatetimeIndex Objects
    * pandas ships with several classes related to datetimes.
    * the Timestamp is similar to Python's datetime object (but with expanded functionality).
    * a DatetimeIndex is an index of Timestamp objects.
    * the Timestamp constructor accepts a string, a datetime object, or equivalent arguments to the datetime class.

In [7]:
pd.Timestamp(2027, 3, 27)

Timestamp('2027-03-27 00:00:00')

In [8]:
pd.Timestamp(dt.date(2020,10,10))

Timestamp('2020-10-10 00:00:00')

In [9]:
pd.Timestamp("2026-02-14")

Timestamp('2026-02-14 00:00:00')

In [10]:
pd.Timestamp("2026/02/14 083314")

Timestamp('2026-02-14 08:33:14')

In [11]:
pd.Series(pd.Timestamp("2026/02/14 083314"))

0   2026-02-14 08:33:14
dtype: datetime64[us]

In [12]:
dt_idx = pd.DatetimeIndex(["2025-02-02","2022-03-10 143312"])
dt_idx

DatetimeIndex(['2025-02-02 00:00:00', '2022-03-10 14:33:12'], dtype='datetime64[us]', freq=None)

In [13]:
dt_idx[1]

Timestamp('2022-03-10 14:33:12')

In [14]:
type(dt_idx)

pandas.DatetimeIndex

### Create Range of Dates with pd.date_range Function
    * the date_range function generates and returns a DatetimeIndex holding a sequence of dates.
    * the function requires 2 of the 3 following parameters: start, end, and period.
    * with start and end, pandas will assume a daily period/interval.
    * every element within a DatetimeIndex is a Timestamp.

In [15]:
pd.date_range(start="2026-01-01", end="2027-01-31") # default interval is 1 day

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10',
               ...
               '2027-01-22', '2027-01-23', '2027-01-24', '2027-01-25',
               '2027-01-26', '2027-01-27', '2027-01-28', '2027-01-29',
               '2027-01-30', '2027-01-31'],
              dtype='datetime64[us]', length=396, freq='D')

In [16]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="2D") # interval of 2 day

DatetimeIndex(['2026-01-01', '2026-01-03', '2026-01-05', '2026-01-07',
               '2026-01-09', '2026-01-11', '2026-01-13', '2026-01-15',
               '2026-01-17', '2026-01-19',
               ...
               '2027-01-12', '2027-01-14', '2027-01-16', '2027-01-18',
               '2027-01-20', '2027-01-22', '2027-01-24', '2027-01-26',
               '2027-01-28', '2027-01-30'],
              dtype='datetime64[us]', length=198, freq='2D')

In [17]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="B") # interval of 1 Business Day

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-06',
               '2026-01-07', '2026-01-08', '2026-01-09', '2026-01-12',
               '2026-01-13', '2026-01-14',
               ...
               '2027-01-18', '2027-01-19', '2027-01-20', '2027-01-21',
               '2027-01-22', '2027-01-25', '2027-01-26', '2027-01-27',
               '2027-01-28', '2027-01-29'],
              dtype='datetime64[us]', length=282, freq='B')

In [18]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="W") # interval of Weekly

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08', '2026-02-15', '2026-02-22',
               '2026-03-01', '2026-03-08', '2026-03-15', '2026-03-22',
               '2026-03-29', '2026-04-05', '2026-04-12', '2026-04-19',
               '2026-04-26', '2026-05-03', '2026-05-10', '2026-05-17',
               '2026-05-24', '2026-05-31', '2026-06-07', '2026-06-14',
               '2026-06-21', '2026-06-28', '2026-07-05', '2026-07-12',
               '2026-07-19', '2026-07-26', '2026-08-02', '2026-08-09',
               '2026-08-16', '2026-08-23', '2026-08-30', '2026-09-06',
               '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04',
               '2026-10-11', '2026-10-18', '2026-10-25', '2026-11-01',
               '2026-11-08', '2026-11-15', '2026-11-22', '2026-11-29',
               '2026-12-06', '2026-12-13', '2026-12-20', '2026-12-27',
               '2027-01-03', '2027-01-10', '2027-01-17', '2027-01-24',
               '2027-01-31'],
              dtype='datetime64[us]', freq='W-SUN')

In [19]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="W-FRI") # interval of Weekly Friday

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06', '2026-02-13', '2026-02-20',
               '2026-02-27', '2026-03-06', '2026-03-13', '2026-03-20',
               '2026-03-27', '2026-04-03', '2026-04-10', '2026-04-17',
               '2026-04-24', '2026-05-01', '2026-05-08', '2026-05-15',
               '2026-05-22', '2026-05-29', '2026-06-05', '2026-06-12',
               '2026-06-19', '2026-06-26', '2026-07-03', '2026-07-10',
               '2026-07-17', '2026-07-24', '2026-07-31', '2026-08-07',
               '2026-08-14', '2026-08-21', '2026-08-28', '2026-09-04',
               '2026-09-11', '2026-09-18', '2026-09-25', '2026-10-02',
               '2026-10-09', '2026-10-16', '2026-10-23', '2026-10-30',
               '2026-11-06', '2026-11-13', '2026-11-20', '2026-11-27',
               '2026-12-04', '2026-12-11', '2026-12-18', '2026-12-25',
               '2027-01-01', '2027-01-08', '2027-01-15', '2027-01-22',
               '2027-01-29'],
              dtype='datetime64[us]', freq='W-FRI')

In [20]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="h") # Hourly interval

DatetimeIndex(['2026-01-01 00:00:00', '2026-01-01 01:00:00',
               '2026-01-01 02:00:00', '2026-01-01 03:00:00',
               '2026-01-01 04:00:00', '2026-01-01 05:00:00',
               '2026-01-01 06:00:00', '2026-01-01 07:00:00',
               '2026-01-01 08:00:00', '2026-01-01 09:00:00',
               ...
               '2027-01-30 15:00:00', '2027-01-30 16:00:00',
               '2027-01-30 17:00:00', '2027-01-30 18:00:00',
               '2027-01-30 19:00:00', '2027-01-30 20:00:00',
               '2027-01-30 21:00:00', '2027-01-30 22:00:00',
               '2027-01-30 23:00:00', '2027-01-31 00:00:00'],
              dtype='datetime64[us]', length=9481, freq='h')

In [21]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="6h") # 6 Hourly interval

DatetimeIndex(['2026-01-01 00:00:00', '2026-01-01 06:00:00',
               '2026-01-01 12:00:00', '2026-01-01 18:00:00',
               '2026-01-02 00:00:00', '2026-01-02 06:00:00',
               '2026-01-02 12:00:00', '2026-01-02 18:00:00',
               '2026-01-03 00:00:00', '2026-01-03 06:00:00',
               ...
               '2027-01-28 18:00:00', '2027-01-29 00:00:00',
               '2027-01-29 06:00:00', '2027-01-29 12:00:00',
               '2027-01-29 18:00:00', '2027-01-30 00:00:00',
               '2027-01-30 06:00:00', '2027-01-30 12:00:00',
               '2027-01-30 18:00:00', '2027-01-31 00:00:00'],
              dtype='datetime64[us]', length=1581, freq='6h')

In [22]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="ME") # End of Monthly interval

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31',
               '2027-01-31'],
              dtype='datetime64[us]', freq='ME')

In [23]:
pd.date_range(start="2026-01-01", end="2027-01-31", freq="MS") # Start of Monthly interval

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01',
               '2027-01-01'],
              dtype='datetime64[us]', freq='MS')

In [24]:
pd.date_range(start="2026-01-01", end="2030-01-31", freq="YS") # Start of Annually interval

DatetimeIndex(['2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01',
               '2030-01-01'],
              dtype='datetime64[us]', freq='YS-JAN')

In [25]:
pd.date_range(start="2026-01-01", end="2030-01-31", freq="YE") # End of Annually interval

DatetimeIndex(['2026-12-31', '2027-12-31', '2028-12-31', '2029-12-31'], dtype='datetime64[us]', freq='YE-DEC')

In [26]:
pd.date_range(start="2026-01-01", freq="MS", periods=24) # Start of Monthly interval for 24 periods.

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01',
               '2027-01-01', '2027-02-01', '2027-03-01', '2027-04-01',
               '2027-05-01', '2027-06-01', '2027-07-01', '2027-08-01',
               '2027-09-01', '2027-10-01', '2027-11-01', '2027-12-01'],
              dtype='datetime64[us]', freq='MS')

In [27]:
pd.date_range(end="2050-12-31", freq="ME", periods=24) # Month-Endly interval for 24 periods to end date.

DatetimeIndex(['2049-01-31', '2049-02-28', '2049-03-31', '2049-04-30',
               '2049-05-31', '2049-06-30', '2049-07-31', '2049-08-31',
               '2049-09-30', '2049-10-31', '2049-11-30', '2049-12-31',
               '2050-01-31', '2050-02-28', '2050-03-31', '2050-04-30',
               '2050-05-31', '2050-06-30', '2050-07-31', '2050-08-31',
               '2050-09-30', '2050-10-31', '2050-11-30', '2050-12-31'],
              dtype='datetime64[us]', freq='ME')

### The dt Attribute
    * the dt attribute reveals a DatetimeProperties object with attributes/methods for working with datetimes. It is similar to the str attribute for string methods.
    * the DatetimeProperties object has attributes like day, month, and year to reveal information about each date in the Series.
    * the day_name method returns the written day of the week.
    * attributes like is_month_end and is_quarter_start return Boolean Series.

In [28]:
ds = pd.Series(pd.date_range(start="2026-01-01", end="2030-01-31", freq="24D 3h")) # interval of 24 days 3 hours
ds

0    2026-01-01 00:00:00
1    2026-01-25 03:00:00
2    2026-02-18 06:00:00
3    2026-03-14 09:00:00
4    2026-04-07 12:00:00
             ...
57   2029-10-07 03:00:00
58   2029-10-31 06:00:00
59   2029-11-24 09:00:00
60   2029-12-18 12:00:00
61   2030-01-11 15:00:00
Length: 62, dtype: datetime64[us]

In [29]:
ds.dt.day

0      1
1     25
2     18
3     14
4      7
      ..
57     7
58    31
59    24
60    18
61    11
Length: 62, dtype: int32

In [30]:
ds.dt.month

0      1
1      1
2      2
3      3
4      4
      ..
57    10
58    10
59    11
60    12
61     1
Length: 62, dtype: int32

In [31]:
ds.dt.year

0     2026
1     2026
2     2026
3     2026
4     2026
      ...
57    2029
58    2029
59    2029
60    2029
61    2030
Length: 62, dtype: int32

In [32]:
ds.dt.hour

0      0
1      3
2      6
3      9
4     12
      ..
57     3
58     6
59     9
60    12
61    15
Length: 62, dtype: int32

In [33]:
ds.dt.day_of_year

0       1
1      25
2      49
3      73
4      97
     ...
57    280
58    304
59    328
60    352
61     11
Length: 62, dtype: int32

In [34]:
ds.dt.day_name()

0      Thursday
1        Sunday
2     Wednesday
3      Saturday
4       Tuesday
        ...
57       Sunday
58    Wednesday
59     Saturday
60      Tuesday
61       Friday
Length: 62, dtype: str

In [35]:
ds.dt.day_of_week

0     3
1     6
2     2
3     5
4     1
     ..
57    6
58    2
59    5
60    1
61    4
Length: 62, dtype: int32

In [36]:
ds.dt.month_name()

0      January
1      January
2     February
3        March
4        April
        ...
57     October
58     October
59    November
60    December
61     January
Length: 62, dtype: str

In [ ]:
ds.dt.is_month_end

0     False
1     False
2     False
3     False
4     False
      ...
57    False
58     True
59    False
60    False
61    False
Length: 62, dtype: bool

In [ ]:
ds[ds.dt.is_month_end]

34   2028-03-31 06:00:00
58   2029-10-31 06:00:00
dtype: datetime64[us]

### Selecting Rows from a DataFrame with a DateTimeIndex
    * the iloc accessor is available for index position-based extraction.
    * the loc accessor accepts strings or Timestamps to extract by index label/value. Note that Python's datetime objects will not work.
    * use list slicing to extract a sequence of dates. The truncate method is another alternative.

In [39]:
ibm = pd.read_csv("data/ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
ibm

                 Open       High        Low      Close        Volume
Date
1962-01-02    5.04610    5.04610    4.98716    4.98716  5.935630e+05
1962-01-03    4.98716    5.03292    4.98716    5.03292  4.451750e+05
1962-01-04    5.03292    5.03292    4.98052    4.98052  3.995136e+05
1962-01-05    4.97389    4.97389    4.87511    4.88166  5.593215e+05
1962-01-08    4.88166    4.88166    4.75059    4.78972  8.332738e+05
...               ...        ...        ...        ...           ...
2023-10-05  140.90000  141.70000  140.19000  141.52000  3.223910e+06
2023-10-06  141.40000  142.94000  140.11000  142.03000  3.511347e+06
2023-10-09  142.30000  142.40000  140.68000  142.20000  2.354396e+06
2023-10-10  142.60000  143.41500  141.72000  142.11000  3.015784e+06
2023-10-11  142.51000  143.34000  142.14000  143.23000  2.511459e+06

[15546 rows x 5 columns]

In [40]:
ibm.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 15546 entries, 1962-01-02 to 2023-10-11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    15546 non-null  float64
 1   High    15546 non-null  float64
 2   Low     15546 non-null  float64
 3   Close   15546 non-null  float64
 4   Volume  15545 non-null  float64
dtypes: float64(5)
memory usage: 728.7 KB

In [41]:
# IMPORTANT NOTE: without the parse_dates, Pandas will NOT create a DatetimeIndex.
ibm2 = pd.read_csv("data/ibm.csv", index_col="Date").sort_index()
ibm2.info()

<class 'pandas.DataFrame'>
Index: 15546 entries, 1962-01-02 to 2023-10-11
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    15546 non-null  float64
 1   High    15546 non-null  float64
 2   Low     15546 non-null  float64
 3   Close   15546 non-null  float64
 4   Volume  15545 non-null  float64
dtypes: float64(5)
memory usage: 728.7+ KB

In [42]:
ibm.iloc[300]

Open           3.561240
High           3.574410
Low            3.554500
Close          3.561240
Volume    536491.781438
Name: 1963-03-12 00:00:00, dtype: float64

In [43]:
ibm.loc["2014-03-04"]

Open      1.288700e+02
High      1.298270e+02
Low       1.288020e+02
Close     1.293290e+02
Volume    6.825202e+06
Name: 2014-03-04 00:00:00, dtype: float64

In [44]:
ibm.loc[pd.Timestamp("2014-03-04")]

Open      1.288700e+02
High      1.298270e+02
Low       1.288020e+02
Close     1.293290e+02
Volume    6.825202e+06
Name: 2014-03-04 00:00:00, dtype: float64

In [45]:
ibm.loc["2014-03-04":"2014-12-31"]

               Open     High      Low    Close        Volume
Date
2014-03-04  128.870  129.827  128.802  129.329  6.825202e+06
2014-03-05  129.407  130.344  129.319  129.807  5.027617e+06
2014-03-06  129.963  130.676  129.631  130.159  5.503611e+06
2014-03-07  130.676  131.047  129.837  130.198  5.936539e+06
2014-03-10  130.090  130.666  128.890  129.309  6.623102e+06
...             ...      ...      ...      ...           ...
2014-12-24  115.119  115.188  114.183  114.359  2.646416e+06
2014-12-26  114.651  115.257  114.495  114.700  2.706324e+06
2014-12-29  114.485  114.700  112.661  113.412  4.715249e+06
2014-12-30  113.090  113.656  112.934  113.109  4.004903e+06
2014-12-31  113.324  114.105  113.304  113.354  5.677519e+06

[211 rows x 5 columns]

In [46]:
# alternative way to retrieve a range of data
ibm.truncate("2014-03-04","2014-12-31")

               Open     High      Low    Close        Volume
Date
2014-03-04  128.870  129.827  128.802  129.329  6.825202e+06
2014-03-05  129.407  130.344  129.319  129.807  5.027617e+06
2014-03-06  129.963  130.676  129.631  130.159  5.503611e+06
2014-03-07  130.676  131.047  129.837  130.198  5.936539e+06
2014-03-10  130.090  130.666  128.890  129.309  6.623102e+06
...             ...      ...      ...      ...           ...
2014-12-24  115.119  115.188  114.183  114.359  2.646416e+06
2014-12-26  114.651  115.257  114.495  114.700  2.706324e+06
2014-12-29  114.485  114.700  112.661  113.412  4.715249e+06
2014-12-30  113.090  113.656  112.934  113.109  4.004903e+06
2014-12-31  113.324  114.105  113.304  113.354  5.677519e+06

[211 rows x 5 columns]

In [47]:
ibm.loc["2014-03-04":"2014-12-31", "Low":"Volume"]

                Low    Close        Volume
Date
2014-03-04  128.802  129.329  6.825202e+06
2014-03-05  129.319  129.807  5.027617e+06
2014-03-06  129.631  130.159  5.503611e+06
2014-03-07  129.837  130.198  5.936539e+06
2014-03-10  128.890  129.309  6.623102e+06
...             ...      ...           ...
2014-12-24  114.183  114.359  2.646416e+06
2014-12-26  114.495  114.700  2.706324e+06
2014-12-29  112.661  113.412  4.715249e+06
2014-12-30  112.934  113.109  4.004903e+06
2014-12-31  113.304  113.354  5.677519e+06

[211 rows x 3 columns]

### The DateOffset Object
    * a DateOffset object adds time to a Timestamp to arrive at a new Timestamp.
    * the DateOffset constructor accepts days, weeks, months, years parameters, and more.
    * we can pass a DateOffset object to the freq parameter of the pd.date_range function.

In [48]:
ibm

                 Open       High        Low      Close        Volume
Date
1962-01-02    5.04610    5.04610    4.98716    4.98716  5.935630e+05
1962-01-03    4.98716    5.03292    4.98716    5.03292  4.451750e+05
1962-01-04    5.03292    5.03292    4.98052    4.98052  3.995136e+05
1962-01-05    4.97389    4.97389    4.87511    4.88166  5.593215e+05
1962-01-08    4.88166    4.88166    4.75059    4.78972  8.332738e+05
...               ...        ...        ...        ...           ...
2023-10-05  140.90000  141.70000  140.19000  141.52000  3.223910e+06
2023-10-06  141.40000  142.94000  140.11000  142.03000  3.511347e+06
2023-10-09  142.30000  142.40000  140.68000  142.20000  2.354396e+06
2023-10-10  142.60000  143.41500  141.72000  142.11000  3.015784e+06
2023-10-11  142.51000  143.34000  142.14000  143.23000  2.511459e+06

[15546 rows x 5 columns]

In [49]:
ibm_idx = ibm.index
ibm_idx

DatetimeIndex(['1962-01-02', '1962-01-03', '1962-01-04', '1962-01-05',
               '1962-01-08', '1962-01-09', '1962-01-10', '1962-01-11',
               '1962-01-12', '1962-01-15',
               ...
               '2023-09-28', '2023-09-29', '2023-10-02', '2023-10-03',
               '2023-10-04', '2023-10-05', '2023-10-06', '2023-10-09',
               '2023-10-10', '2023-10-11'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [50]:
ibm_idx + pd.DateOffset(days=5)

DatetimeIndex(['1962-01-07', '1962-01-08', '1962-01-09', '1962-01-10',
               '1962-01-13', '1962-01-14', '1962-01-15', '1962-01-16',
               '1962-01-17', '1962-01-20',
               ...
               '2023-10-03', '2023-10-04', '2023-10-07', '2023-10-08',
               '2023-10-09', '2023-10-10', '2023-10-11', '2023-10-14',
               '2023-10-15', '2023-10-16'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [51]:
ibm_idx - pd.DateOffset(days=5)

DatetimeIndex(['1961-12-28', '1961-12-29', '1961-12-30', '1961-12-31',
               '1962-01-03', '1962-01-04', '1962-01-05', '1962-01-06',
               '1962-01-07', '1962-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-27', '2023-09-28',
               '2023-09-29', '2023-09-30', '2023-10-01', '2023-10-04',
               '2023-10-05', '2023-10-06'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [52]:
ibm_idx + pd.DateOffset(months=3)

DatetimeIndex(['1962-04-02', '1962-04-03', '1962-04-04', '1962-04-05',
               '1962-04-08', '1962-04-09', '1962-04-10', '1962-04-11',
               '1962-04-12', '1962-04-15',
               ...
               '2023-12-28', '2023-12-29', '2024-01-02', '2024-01-03',
               '2024-01-04', '2024-01-05', '2024-01-06', '2024-01-09',
               '2024-01-10', '2024-01-11'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [53]:
ibm_idx + pd.DateOffset(months=3, days=2)

DatetimeIndex(['1962-04-04', '1962-04-05', '1962-04-06', '1962-04-07',
               '1962-04-10', '1962-04-11', '1962-04-12', '1962-04-13',
               '1962-04-14', '1962-04-17',
               ...
               '2023-12-30', '2023-12-31', '2024-01-04', '2024-01-05',
               '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-11',
               '2024-01-12', '2024-01-13'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [54]:
# find the ibm stock price on every one of my birthdays
birthdays = pd.date_range(start="1960-06-14", end="2023-06-14", freq=pd.DateOffset(years=1))
ibm[ibm.index.isin(birthdays)]

                 Open       High        Low      Close        Volume
Date
1962-06-14    2.81212    2.89107    2.61528    2.66729  1.017052e+07
1963-06-14    4.04080    4.06022    4.02783    4.04080  5.136621e+05
1965-06-14    4.96052    5.01975    4.88166    4.92792  1.187135e+06
1966-06-14    5.64405    5.65712    5.56530    5.65712  9.679690e+05
1967-06-14    8.03701    8.20204    7.97015    8.16671  1.485437e+06
1968-06-14   11.74030   11.74030   11.51290   11.63590  1.384987e+06
1971-06-14   10.57900   10.57900   10.39940   10.42000  1.388028e+06
1972-06-14   12.91830   13.07640   12.91830   13.07640  1.074505e+06
1973-06-14   13.43070   13.43070   13.08220   13.11930  1.105554e+06
1974-06-14    9.27223    9.27223    9.10633    9.10633  7.646361e+05
1976-06-14   10.59260   10.66580   10.59260   10.64540  2.661607e+06
1977-06-14   10.38580   10.57220   10.38580   10.57220  3.353187e+06
1978-06-14   11.21820   11.29830   11.08650   11.08650  4.772878e+06
1979-06-14   12.30540   12.30540   12.06240   12.20870  3.824997e+06
1982-06-14    9.71042    9.73579    9.67138    9.67138  2.413836e+06
1983-06-14   19.18270   19.59260   19.14180   19.30470  5.914347e+06
1984-06-14   17.01710   17.03670   16.44820   16.48330  1.215136e+07
1985-06-14   19.55550   19.81420   19.53210   19.81420  1.066592e+07
1988-06-14   19.47450   19.59260   19.35060   19.42870  1.455241e+07
1989-06-14   18.20680   18.24490   17.93450   18.06140  7.276201e+06
1990-06-14   19.84240   19.94290   19.65800   19.78390  1.033900e+07
1991-06-14   16.59170   16.62680   16.34770   16.42480  1.437951e+07
1993-06-14    8.55601    8.59455    8.48788    8.50857  7.151397e+06
1994-06-14   10.45500   10.63660   10.45500   10.63660  1.691571e+07
1995-06-14   15.03800   15.28490   15.03800   15.22440  1.560012e+07
1996-06-14   16.92060   17.06590   16.63460   16.63460  1.651209e+07
1999-06-14   75.87690   75.95300   74.64240   75.61150  7.452602e+06
2000-06-14   77.80730   78.55490   75.58810   75.92960  8.039924e+06
2001-06-14   75.95990   76.26240   74.89420   76.04870  1.109405e+07
2002-06-14   48.74930   50.44350   48.12960   50.04720  1.307671e+07
2004-06-14   59.16720   59.51460   58.88320   59.17790  6.272314e+06
2005-06-14   49.30940   49.56020   49.10060   49.20400  6.573057e+06
2006-06-14   50.54780   51.15000   50.54780   51.05920  9.133912e+06
2007-06-14   67.74160   68.49120   67.55140   68.23260  7.861855e+06
2010-06-14   84.42800   85.40480   84.42800   84.43680  1.027181e+07
2011-06-14  108.22000  108.60000  108.02500  108.31800  1.065174e+07
2012-06-14  129.49500  131.37900  129.32900  130.90000  5.343375e+06
2013-06-14  139.26400  139.78100  137.79000  138.05400  4.107529e+06
2016-06-14  112.56300  112.99200  111.91900  112.43500  3.848837e+06
2017-06-14  118.70200  119.44300  117.91100  118.57400  3.948065e+06
2018-06-14  117.84300  118.07700  116.57400  116.66200  4.140145e+06
2019-06-14  114.02600  114.39700  113.16800  113.80200  2.605177e+06
2021-06-14  140.08400  140.38600  138.16200  139.45900  3.598537e+06
2022-06-14  131.74900  133.65200  131.61300  132.45200  4.721470e+06
2023-06-14  137.80000  138.93000  136.94000  137.20000  4.514888e+06

### Specialized Date Offsets
    * pandas nests more specialized date offsets in pd.tseries.offsets.
    * we can add a different amount of time to each date (e.g. month end, quarter end, year begin)

In [55]:
ibm

                 Open       High        Low      Close        Volume
Date
1962-01-02    5.04610    5.04610    4.98716    4.98716  5.935630e+05
1962-01-03    4.98716    5.03292    4.98716    5.03292  4.451750e+05
1962-01-04    5.03292    5.03292    4.98052    4.98052  3.995136e+05
1962-01-05    4.97389    4.97389    4.87511    4.88166  5.593215e+05
1962-01-08    4.88166    4.88166    4.75059    4.78972  8.332738e+05
...               ...        ...        ...        ...           ...
2023-10-05  140.90000  141.70000  140.19000  141.52000  3.223910e+06
2023-10-06  141.40000  142.94000  140.11000  142.03000  3.511347e+06
2023-10-09  142.30000  142.40000  140.68000  142.20000  2.354396e+06
2023-10-10  142.60000  143.41500  141.72000  142.11000  3.015784e+06
2023-10-11  142.51000  143.34000  142.14000  143.23000  2.511459e+06

[15546 rows x 5 columns]

In [56]:
ibm.index

DatetimeIndex(['1962-01-02', '1962-01-03', '1962-01-04', '1962-01-05',
               '1962-01-08', '1962-01-09', '1962-01-10', '1962-01-11',
               '1962-01-12', '1962-01-15',
               ...
               '2023-09-28', '2023-09-29', '2023-10-02', '2023-10-03',
               '2023-10-04', '2023-10-05', '2023-10-06', '2023-10-09',
               '2023-10-10', '2023-10-11'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [ ]:
# rounding the date to the end of month with specialized offsets object
ibm.index + pd.tseries.offsets.MonthEnd()

DatetimeIndex(['1962-01-31', '1962-01-31', '1962-01-31', '1962-01-31',
               '1962-01-31', '1962-01-31', '1962-01-31', '1962-01-31',
               '1962-01-31', '1962-01-31',
               ...
               '2023-09-30', '2023-09-30', '2023-10-31', '2023-10-31',
               '2023-10-31', '2023-10-31', '2023-10-31', '2023-10-31',
               '2023-10-31', '2023-10-31'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [59]:
# rounding the date to the end of previous month
ibm.index - pd.tseries.offsets.MonthEnd()

DatetimeIndex(['1961-12-31', '1961-12-31', '1961-12-31', '1961-12-31',
               '1961-12-31', '1961-12-31', '1961-12-31', '1961-12-31',
               '1961-12-31', '1961-12-31',
               ...
               '2023-08-31', '2023-08-31', '2023-09-30', '2023-09-30',
               '2023-09-30', '2023-09-30', '2023-09-30', '2023-09-30',
               '2023-09-30', '2023-09-30'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [60]:
# move date to next end quarter
ibm.index + pd.tseries.offsets.QuarterEnd()

DatetimeIndex(['1962-03-31', '1962-03-31', '1962-03-31', '1962-03-31',
               '1962-03-31', '1962-03-31', '1962-03-31', '1962-03-31',
               '1962-03-31', '1962-03-31',
               ...
               '2023-09-30', '2023-09-30', '2023-12-31', '2023-12-31',
               '2023-12-31', '2023-12-31', '2023-12-31', '2023-12-31',
               '2023-12-31', '2023-12-31'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [61]:
# move date to previous end quarter
ibm.index - pd.tseries.offsets.QuarterEnd()

DatetimeIndex(['1961-12-31', '1961-12-31', '1961-12-31', '1961-12-31',
               '1961-12-31', '1961-12-31', '1961-12-31', '1961-12-31',
               '1961-12-31', '1961-12-31',
               ...
               '2023-06-30', '2023-06-30', '2023-09-30', '2023-09-30',
               '2023-09-30', '2023-09-30', '2023-09-30', '2023-09-30',
               '2023-09-30', '2023-09-30'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [63]:
# move date to next beginning quarter, with starting month as Jan. Default is 3 or Mar
ibm.index + pd.tseries.offsets.QuarterBegin(startingMonth=1)

DatetimeIndex(['1962-04-01', '1962-04-01', '1962-04-01', '1962-04-01',
               '1962-04-01', '1962-04-01', '1962-04-01', '1962-04-01',
               '1962-04-01', '1962-04-01',
               ...
               '2023-10-01', '2023-10-01', '2024-01-01', '2024-01-01',
               '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
               '2024-01-01', '2024-01-01'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [65]:
# move date to next beginning quarter, with default starting month. Default is 3 or Mar
ibm.index + pd.tseries.offsets.QuarterBegin()

DatetimeIndex(['1962-03-01', '1962-03-01', '1962-03-01', '1962-03-01',
               '1962-03-01', '1962-03-01', '1962-03-01', '1962-03-01',
               '1962-03-01', '1962-03-01',
               ...
               '2023-12-01', '2023-12-01', '2023-12-01', '2023-12-01',
               '2023-12-01', '2023-12-01', '2023-12-01', '2023-12-01',
               '2023-12-01', '2023-12-01'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [66]:
# move date to previous beginning quarter, with starting month as Jan. Default is 3 or Mar
ibm.index - pd.tseries.offsets.QuarterBegin(startingMonth=1)

DatetimeIndex(['1962-01-01', '1962-01-01', '1962-01-01', '1962-01-01',
               '1962-01-01', '1962-01-01', '1962-01-01', '1962-01-01',
               '1962-01-01', '1962-01-01',
               ...
               '2023-07-01', '2023-07-01', '2023-10-01', '2023-10-01',
               '2023-10-01', '2023-10-01', '2023-10-01', '2023-10-01',
               '2023-10-01', '2023-10-01'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [67]:
# move date to next beginning of year
ibm.index + pd.tseries.offsets.YearBegin()

DatetimeIndex(['1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01',
               ...
               '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
               '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
               '2024-01-01', '2024-01-01'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

In [68]:
# move date to previous beginning of year
ibm.index - pd.tseries.offsets.YearBegin()

DatetimeIndex(['1962-01-01', '1962-01-01', '1962-01-01', '1962-01-01',
               '1962-01-01', '1962-01-01', '1962-01-01', '1962-01-01',
               '1962-01-01', '1962-01-01',
               ...
               '2023-01-01', '2023-01-01', '2023-01-01', '2023-01-01',
               '2023-01-01', '2023-01-01', '2023-01-01', '2023-01-01',
               '2023-01-01', '2023-01-01'],
              dtype='datetime64[us]', name='Date', length=15546, freq=None)

### Timedeltas
    * a Timedelta is a pandas object that represents a duration (an amount of time).
    * subtracting two Timestamp objects will yield a Timedelta object (this applies to subtracting a Series from another Series).
    * the Timedelta constructor accepts parameters for time as well as string descriptions.

In [69]:
pd.Timestamp("2023-03-31") - pd.Timestamp("2023-03-20")

Timedelta('11 days 00:00:00')

In [70]:
pd.Timestamp("2023-03-31 12:30:22") - pd.Timestamp("2023-03-20 19:24:55")

Timedelta('10 days 17:05:27')

In [71]:
pd.Timestamp("2023-03-20 19:24:55") - pd.Timestamp("2023-03-31 12:30:22")

Timedelta('-11 days +06:54:33')

In [72]:
pd.Timedelta(days=3, hours=2, minutes=5)

Timedelta('3 days 02:05:00')

In [73]:
pd.Timedelta("5 minutes")

Timedelta('0 days 00:05:00')

In [74]:
pd.Timedelta("3 days 2 hours 5 minutes")

Timedelta('3 days 02:05:00')

In [75]:
ecomm = pd.read_csv("data/ecommerce.csv", index_col="ID", parse_dates=["order_date","delivery_date"], date_format="%m/%d/%y")
ecomm

    order_date delivery_date
ID
1   1998-05-24    1999-02-05
2   1992-04-22    1998-03-06
4   1991-02-10    1992-08-26
5   1992-07-21    1997-11-20
7   1993-09-02    1998-06-10
..         ...           ...
990 1991-06-24    1996-02-02
991 1991-09-09    1998-03-30
993 1990-11-16    1998-04-27
994 1993-06-03    1993-06-13
997 1990-01-04    1991-10-03

[501 rows x 2 columns]

In [76]:
ecomm.dtypes

order_date       datetime64[us]
delivery_date    datetime64[us]
dtype: object

In [78]:
# we want to know how long it takes between order date and delivery date
ecomm["Delivery Time"] = ecomm["delivery_date"] - ecomm["order_date"]
ecomm

    order_date delivery_date Delivery Time
ID
1   1998-05-24    1999-02-05      257 days
2   1992-04-22    1998-03-06     2144 days
4   1991-02-10    1992-08-26      563 days
5   1992-07-21    1997-11-20     1948 days
7   1993-09-02    1998-06-10     1742 days
..         ...           ...           ...
990 1991-06-24    1996-02-02     1684 days
991 1991-09-09    1998-03-30     2394 days
993 1990-11-16    1998-04-27     2719 days
994 1993-06-03    1993-06-13       10 days
997 1990-01-04    1991-10-03      637 days

[501 rows x 3 columns]

In [79]:
ecomm["If it Took Twice As Long"] = ecomm["delivery_date"] + ecomm["Delivery Time"] 
ecomm

    order_date delivery_date Delivery Time If it Took Twice As Long
ID
1   1998-05-24    1999-02-05      257 days               1999-10-20
2   1992-04-22    1998-03-06     2144 days               2004-01-18
4   1991-02-10    1992-08-26      563 days               1994-03-12
5   1992-07-21    1997-11-20     1948 days               2003-03-22
7   1993-09-02    1998-06-10     1742 days               2003-03-18
..         ...           ...           ...                      ...
990 1991-06-24    1996-02-02     1684 days               2000-09-12
991 1991-09-09    1998-03-30     2394 days               2004-10-18
993 1990-11-16    1998-04-27     2719 days               2005-10-06
994 1993-06-03    1993-06-13       10 days               1993-06-23
997 1990-01-04    1991-10-03      637 days               1993-07-01

[501 rows x 4 columns]

In [80]:
ecomm.dtypes

order_date                   datetime64[us]
delivery_date                datetime64[us]
Delivery Time               timedelta64[us]
If it Took Twice As Long     datetime64[us]
dtype: object

In [81]:
ecomm["Delivery Time"].max()

Timedelta('3583 days 00:00:00')

In [82]:
ecomm["Delivery Time"].min()

Timedelta('8 days 00:00:00')

In [83]:
ecomm["Delivery Time"].mean()

Timedelta('1217 days 22:53:53.532934')