## Input and Output

In [1]:
import pandas as pd

url = "https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv"

baby_names = pd.read_csv(url)
baby_names

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Chloe,71,1
1,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Olivia,71,1
2,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Emma,66,2
3,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Mia,59,3
4,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Ava,53,4
...,...,...,...,...,...,...
21607,2011,MALE,WHITE NON HISPANIC,BENNETT,10,97
21608,2011,MALE,WHITE NON HISPANIC,BERISH,10,97
21609,2011,MALE,WHITE NON HISPANIC,REED,10,97
21610,2011,MALE,WHITE NON HISPANIC,NIKOLAS,10,97
21611,2011,MALE,WHITE NON HISPANIC,DEREK,10,97

### Export DataFrame to CSV File
    * the to_csv method exports a DataFrame to a CSV file.
    * its first argument is the filename.
    * by default, pandas will include the index. Set the index parameter to False to exclude the index.
    * the columns parameter limits the exported columns.

In [2]:
baby_names.to_csv("data/baby_names.csv", index=False, columns=["Year of Birth", "Child's First Name","Count"])

### Import Excel File into Pandas
    * the read_excel function reads an Excel file/workbook into a DataFrame.
    * use the sheet_name parameter if the workbook contains multiple worksheets. Pass a single worksheet name or a list of worksheet names/index positions.
    * pass the sheet_name parameter an argument of None to include all worksheets.
    * pandas will store multiple worksheets in a Python dictionary. The keys will be the worksheet names, and the values will be the DataFrames.

In [3]:
pd.read_excel("data/Data - Single Worksheet.xlsx")

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [4]:
dic = pd.read_excel("data/Data - Multiple Worksheets.xlsx", sheet_name=["Data 1","Data 2"])

In [5]:
df1 = dic["Data 1"]
df2 = dic["Data 2"]

In [6]:
df2

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [7]:
df1

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [8]:
dic = pd.read_excel("data/Data - Multiple Worksheets.xlsx", sheet_name=[0, 1]) # same as the above 
df1 = dic[0]
df2 = dic[1]

In [9]:
df1

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [10]:
df2

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [11]:
dic = pd.read_excel("data/Data - Multiple Worksheets.xlsx", sheet_name=None) # brings in all the worksheets
dic

{'Data 1':   First Name Last Name           City Gender
 0    Brandon     James          Miami      M
 1       Sean   Hawkins         Denver      M
 2       Judy       Day    Los Angeles      F
 3     Ashley      Ruiz  San Francisco      F
 4  Stephanie     Gomez       Portland      F,
 'Data 2':   First Name Last Name           City Gender
 0     Parker     Power        Raleigh      F
 1    Preston  Prescott   Philadelphia      F
 2    Ronaldo   Donaldo         Bangor      M
 3      Megan   Stiller  San Francisco      M
 4     Bustin    Jieber         Austin      F}

### Export Excel File from Pandas
    * the ExcelWriter class writes one or more DataFrames to an Excel file.
    * use a context manager (the with keyword) in combination with the ExcelWriter object and an assigned variable.
    * invoke the to_excel method on every DataFrame to include in the Excel workbook and pass in the ExcelWriter object as the first argument.
    * the to_excel method supports sheet_name, index, and columns parameters.

In [12]:
baby_names

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Chloe,71,1
1,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Olivia,71,1
2,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Emma,66,2
3,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Mia,59,3
4,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Ava,53,4
...,...,...,...,...,...,...
21607,2011,MALE,WHITE NON HISPANIC,BENNETT,10,97
21608,2011,MALE,WHITE NON HISPANIC,BERISH,10,97
21609,2011,MALE,WHITE NON HISPANIC,REED,10,97
21610,2011,MALE,WHITE NON HISPANIC,NIKOLAS,10,97
21611,2011,MALE,WHITE NON HISPANIC,DEREK,10,97

In [13]:
females = baby_names[baby_names["Gender"] == "FEMALE"]
females

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
0,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Chloe,71,1
1,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Olivia,71,1
2,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Emma,66,2
3,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Mia,59,3
4,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,Ava,53,4
...,...,...,...,...,...,...
20648,2011,FEMALE,WHITE NON HISPANIC,LEILA,10,81
20649,2011,FEMALE,WHITE NON HISPANIC,YASMINE,10,81
20650,2011,FEMALE,WHITE NON HISPANIC,QUINN,10,81
20651,2011,FEMALE,WHITE NON HISPANIC,CELIA,10,81
20652,2011,FEMALE,WHITE NON HISPANIC,CHAVY,10,81

In [14]:
males = baby_names[baby_names["Gender"] == "MALE"]
males

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank
893,2021,MALE,ASIAN AND PACIFIC ISLANDER,Muhammad,138,1
894,2021,MALE,ASIAN AND PACIFIC ISLANDER,Ethan,119,2
895,2021,MALE,ASIAN AND PACIFIC ISLANDER,Lucas,115,3
896,2021,MALE,ASIAN AND PACIFIC ISLANDER,Aiden,79,4
897,2021,MALE,ASIAN AND PACIFIC ISLANDER,Jasper,74,5
...,...,...,...,...,...,...
21607,2011,MALE,WHITE NON HISPANIC,BENNETT,10,97
21608,2011,MALE,WHITE NON HISPANIC,BERISH,10,97
21609,2011,MALE,WHITE NON HISPANIC,REED,10,97
21610,2011,MALE,WHITE NON HISPANIC,NIKOLAS,10,97
21611,2011,MALE,WHITE NON HISPANIC,DEREK,10,97

In [15]:
with pd.ExcelWriter("data/NYC Baby Data.xlsx") as xl_file:
    females.to_excel(xl_file, sheet_name="Females", index=False)
    males.to_excel(xl_file, sheet_name="Males", index=False, columns=["Year of Birth", "Child's First Name", "Rank"])